# Regenerates the procedural source assets (sounds: the nine .wav cues of Phase
# 8t). Windows PowerShell 7+. NOTE: parenthesize all arithmetic inside array
# literals - the comma binds tighter than + and silently corrupts data
# otherwise. Everything here is seeded or analytic: rerunning must leave
# `git status` clean apart from whatever was deliberately changed.
#
# ⚑ THE TEXTURE HALF IS GONE TOO, AT PHASE 9's STAGE G, AND FOR THE SAME REASON
# THE MESH HALF WENT. It drew checker/hull/cockpit with System.Drawing and
# committed them as PNG, so the source of a texture was opaque binary, an edit
# was undiffable, the Forge could not open it, and generating one needed Windows
# with .NET present. They live in assets/textures/*.tex now - the same ops this
# script used, written down - and the cooker evaluates them. The transcription
# was proved pixel-exact against the PNGs it replaced before those were deleted.
# The `System.Drawing` dependency left with them; only audio needs this script.
#
# ⚑ THE MESH HALF IS GONE, AND THAT WAS THE POINT OF PHASE 9's D CHECKPOINT.
# This script used to emit every mesh in the game as base64-embedded glTF, and
# from stage B until now there were TWO implementations of those five meshes -
# this one and sol::assets::MeshBuilder - with the suite unable to tell them
# apart, because its ground truth was embedded hashes rather than these files.
# Editing a recipe here and regenerating would have left the C++ port quietly
# describing an asset that no longer existed.
#
# The meshes now live in assets/meshes/*.forge, which the cooker imports
# directly, and geometry.unit READS THOSE FILES. There is one implementation.
# Nothing about a mesh is regenerated by this script any more; if you are here
# looking for Add-Box, it is MeshBuilder::addBox, and the shape it used to build
# is a [[part]] in the .forge file next to the mesh you want.
$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path "$PSScriptRoot\..\..").Path

# --- shared audio synthesis + WAV emit (Phase 8t) ---
# Mono 16-bit PCM. Mono because a 3D voice can only be panned when the source
# has one channel; the 2D cues are mono too rather than carrying a second
# layout through the pipeline for nothing. Every generator here is seeded, so
# a regenerate is byte-identical - the same property the meshes and textures
# have, and the reason `git status` is the check after running this script.
$audioRate = 44100

function New-Wave($seconds) {
    return New-Object 'double[]' ([int]($audioRate * $seconds))
}

# Exponentially decaying sine sweeping f0 -> f1, with an optional third
# harmonic to square it off a little.
function Add-Tone($buf, $start, $duration, $f0, $f1, $decay, $gain, $harmonic = 0.0) {
    $first = [int]($start * $audioRate)
    $count = [int]($duration * $audioRate)
    $phase = 0.0
    for ($i = 0; $i -lt $count; $i++) {
        $index = $first + $i
        if ($index -ge $buf.Length) { break }
        $t = $i / [double]$audioRate
        $u = $i / [double]$count
        $f = $f0 + (($f1 - $f0) * $u)
        $phase += (2.0 * [math]::PI * $f / $audioRate)
        $env = [math]::Exp(-$t * $decay)
        $s = [math]::Sin($phase) + ($harmonic * [math]::Sin(3.0 * $phase))
        $buf[$index] += ($gain * $env * $s)
    }
}

# Decaying white noise through a one-pole lowpass; the cutoff may sweep.
function Add-NoiseBurst($buf, $start, $duration, $decay, $gain, $cutoff0, $cutoff1, $seed) {
    $first = [int]($start * $audioRate)
    $count = [int]($duration * $audioRate)
    $rng = New-Object System.Random($seed)
    $state = 0.0
    for ($i = 0; $i -lt $count; $i++) {
        $index = $first + $i
        if ($index -ge $buf.Length) { break }
        $t = $i / [double]$audioRate
        $u = $i / [double]$count
        $cutoff = $cutoff0 + (($cutoff1 - $cutoff0) * $u)
        $a = [math]::Exp(-2.0 * [math]::PI * $cutoff / $audioRate)
        $white = ($rng.NextDouble() * 2.0) - 1.0
        $state = ($a * $state) + ((1.0 - $a) * $white)
        $env = [math]::Exp(-$t * $decay)
        $buf[$index] += ($gain * $env * $state)
    }
}

# Noise that survives being looped: generate a tail past the end and crossfade
# it back over the head, so sample 0 continues from the last sample.
function Add-LoopNoise($buf, $gain, $cutoff, $seed) {
    $n = $buf.Length
    $fade = [int]($audioRate * 0.25)
    $rng = New-Object System.Random($seed)
    $scratch = New-Object 'double[]' ($n + $fade)
    $a = [math]::Exp(-2.0 * [math]::PI * $cutoff / $audioRate)
    $state = 0.0
    for ($i = 0; $i -lt $scratch.Length; $i++) {
        $white = ($rng.NextDouble() * 2.0) - 1.0
        $state = ($a * $state) + ((1.0 - $a) * $white)
        $scratch[$i] = $state
    }
    for ($i = 0; $i -lt $n; $i++) {
        $v = $scratch[$i]
        if ($i -lt $fade) {
            $w = $i / [double]$fade
            $v = ($scratch[$i] * $w) + ($scratch[$n + $i] * (1.0 - $w))
        }
        $buf[$i] += ($gain * $v)
    }
}

function Add-Fade($buf, $inSeconds, $outSeconds) {
    $inCount = [int]($inSeconds * $audioRate)
    $outCount = [int]($outSeconds * $audioRate)
    for ($i = 0; $i -lt $inCount -and $i -lt $buf.Length; $i++) {
        $buf[$i] = $buf[$i] * ($i / [double]$inCount)
    }
    for ($i = 0; $i -lt $outCount -and $i -lt $buf.Length; $i++) {
        $index = $buf.Length - 1 - $i
        $buf[$index] = $buf[$index] * ($i / [double]$outCount)
    }
}

function Set-Peak($buf, $peak) {
    $max = 0.0
    foreach ($v in $buf) {
        $abs = [math]::Abs($v)
        if ($abs -gt $max) { $max = $abs }
    }
    if ($max -le 0.0) { return }
    $scale = $peak / $max
    for ($i = 0; $i -lt $buf.Length; $i++) { $buf[$i] = $buf[$i] * $scale }
}

function Write-Wav($buf, $path) {
    $n = $buf.Length
    $dataBytes = $n * 2
    New-Item -ItemType Directory -Force (Split-Path -Parent $path) | Out-Null
    $samples = New-Object 'byte[]' $dataBytes
    for ($i = 0; $i -lt $n; $i++) {
        $v = [int][math]::Round($buf[$i] * 32767.0)
        if ($v -gt 32767) { $v = 32767 } elseif ($v -lt -32768) { $v = -32768 }
        $u = [uint16]($v -band 0xFFFF)
        $samples[$i * 2] = [byte]($u -band 0xFF)
        $samples[($i * 2) + 1] = [byte](($u -shr 8) -band 0xFF)
    }
    $ascii = [System.Text.Encoding]::ASCII
    $stream = [System.IO.File]::Create($path)
    $w = New-Object System.IO.BinaryWriter($stream)
    $w.Write($ascii.GetBytes('RIFF'))
    $w.Write([uint32](36 + $dataBytes))
    $w.Write($ascii.GetBytes('WAVE'))
    $w.Write($ascii.GetBytes('fmt '))
    $w.Write([uint32]16)
    $w.Write([uint16]1)                  # PCM
    $w.Write([uint16]1)                  # mono
    $w.Write([uint32]$audioRate)
    $w.Write([uint32]($audioRate * 2))   # byte rate
    $w.Write([uint16]2)                  # block align
    $w.Write([uint16]16)                 # bits per sample
    $w.Write($ascii.GetBytes('data'))
    $w.Write([uint32]$dataBytes)
    $w.Write($samples)
    $w.Flush()
    $w.Dispose()
    $stream.Dispose()
    Write-Output "wrote $(Split-Path -Leaf $path)"
}

$soundDir = "$repo\assets\sounds"

# weapon_fire: a falling sweep with a bright transient in front of it.
$buf = New-Wave 0.22
Add-Tone $buf 0.0 0.22 1800 320 22.0 0.9
Add-NoiseBurst $buf 0.0 0.05 90.0 0.5 6000 2000 101
Set-Peak $buf 0.85
Add-Fade $buf 0.001 0.02
Write-Wav $buf "$soundDir\weapon_fire.wav"

# weapon_hit_shield: energy, so it rings - two partials and a short tick.
$buf = New-Wave 0.35
Add-Tone $buf 0.0 0.35 900 780 11.0 0.7
Add-Tone $buf 0.0 0.35 1350 1230 14.0 0.4
Add-NoiseBurst $buf 0.0 0.06 70.0 0.35 8000 3000 102
Set-Peak $buf 0.8
Add-Fade $buf 0.001 0.03
Write-Wav $buf "$soundDir\weapon_hit_shield.wav"

# weapon_hit_hull: metal, so it thuds - low body plus grit, no ring.
$buf = New-Wave 0.30
Add-Tone $buf 0.0 0.30 150 70 26.0 0.9
Add-NoiseBurst $buf 0.0 0.18 24.0 0.6 1800 500 103
Set-Peak $buf 0.85
Add-Fade $buf 0.001 0.03
Write-Wav $buf "$soundDir\weapon_hit_hull.wav"

# explosion: broadband collapsing to a rumble.
$buf = New-Wave 1.30
Add-NoiseBurst $buf 0.0 1.30 3.4 1.0 5000 180 104
Add-Tone $buf 0.0 1.30 70 28 4.5 0.8
Add-NoiseBurst $buf 0.0 0.09 40.0 0.5 9000 4000 105
Set-Peak $buf 0.95
Add-Fade $buf 0.001 0.12
Write-Wav $buf "$soundDir\explosion.wav"

# mining_cut: sustained grit with a beam buzz under it. Retriggered while the
# trigger is held, so it decays little and stays short.
$buf = New-Wave 0.45
Add-NoiseBurst $buf 0.0 0.45 4.0 0.7 3000 1200 106
Add-Tone $buf 0.0 0.45 240 210 5.0 0.35 0.25
Set-Peak $buf 0.6
Add-Fade $buf 0.01 0.06
Write-Wav $buf "$soundDir\mining_cut.wav"

# engine_loop: the one looping voice in the game. Integer frequencies over a
# 2 s buffer complete a whole number of cycles, so the tonal layers wrap
# cleanly; the noise layer is crossfaded to do the same.
$buf = New-Wave 2.0
Add-Tone $buf 0.0 2.0 48 48 0.0 0.55
Add-Tone $buf 0.0 2.0 96 96 0.0 0.30
Add-Tone $buf 0.0 2.0 145 145 0.0 0.16
Add-Tone $buf 0.0 2.0 194 194 0.0 0.08
Add-LoopNoise $buf 0.45 900 107
Set-Peak $buf 0.7
Write-Wav $buf "$soundDir\engine_loop.wav"

# ui_click: short enough to feel like the button, not like a sound.
$buf = New-Wave 0.05
Add-Tone $buf 0.0 0.05 2200 1400 90.0 0.8
Add-NoiseBurst $buf 0.0 0.012 200.0 0.4 9000 6000 108
Set-Peak $buf 0.5
Add-Fade $buf 0.0005 0.008
Write-Wav $buf "$soundDir\ui_click.wav"

# docking_chime: two notes a fifth apart, soft and unhurried.
$buf = New-Wave 0.90
Add-Tone $buf 0.0 0.60 660 660 4.0 0.7
Add-Tone $buf 0.22 0.68 988 988 4.0 0.6
Set-Peak $buf 0.65
Add-Fade $buf 0.005 0.08
Write-Wav $buf "$soundDir\docking_chime.wav"

# alarm: a two-tone warble, harmonics on so it cuts through the mix.
$buf = New-Wave 0.90
Add-Tone $buf 0.00 0.15 740 740 1.0 0.7 0.35
Add-Tone $buf 0.15 0.15 580 580 1.0 0.7 0.35
Add-Tone $buf 0.30 0.15 740 740 1.0 0.7 0.35
Add-Tone $buf 0.45 0.15 580 580 1.0 0.7 0.35
Add-Tone $buf 0.60 0.15 740 740 1.0 0.7 0.35
Add-Tone $buf 0.75 0.15 580 580 1.0 0.7 0.35
Set-Peak $buf 0.75
Add-Fade $buf 0.004 0.02
Write-Wav $buf "$soundDir\alarm.wav"
