#include "bc1.hpp"
#include "gltf.hpp"
#include "png.hpp"
#include "sound.hpp"

#include "sol/assets/asset_loader.hpp"
#include "sol/assets/formats.hpp"
#include "sol/platform/file_io.hpp"
#include "sol/test/test.hpp"

#include <cstdio>
#include <cstring>
#include <string>

using namespace sol;

SOL_TEST(base64DecodesKnownVectors)
{
    std::vector<std::uint8_t> out;
    SOL_CHECK(cooker::decodeBase64("aGVsbG8=", 8, out));
    SOL_CHECK(out.size() == 5 && std::memcmp(out.data(), "hello", 5) == 0);
    SOL_CHECK(cooker::decodeBase64("", 0, out) && out.empty());
    SOL_CHECK(!cooker::decodeBase64("a!b", 3, out));
}

SOL_TEST(pngDecodesRgba2x2)
{
    // 2x2 RGBA PNG generated by System.Drawing:
    // (0,0) red, (1,0) green, (0,1) blue, (1,1) white with alpha 128.
    static const std::uint8_t kPng[] = {
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44,
        0x52, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02, 0x08, 0x06, 0x00, 0x00, 0x00, 0x72,
        0xb6, 0x0d, 0x24, 0x00, 0x00, 0x00, 0x01, 0x73, 0x52, 0x47, 0x42, 0x00, 0xae, 0xce, 0x1c,
        0xe9, 0x00, 0x00, 0x00, 0x04, 0x67, 0x41, 0x4d, 0x41, 0x00, 0x00, 0xb1, 0x8f, 0x0b, 0xfc,
        0x61, 0x05, 0x00, 0x00, 0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00, 0x0e, 0xc3, 0x00,
        0x00, 0x0e, 0xc3, 0x01, 0xc7, 0x6f, 0xa8, 0x64, 0x00, 0x00, 0x00, 0x14, 0x49, 0x44, 0x41,
        0x54, 0x18, 0x57, 0x63, 0xf8, 0xcf, 0xc0, 0xf0, 0x1f, 0x0c, 0x19, 0x18, 0xfe, 0x83, 0x40,
        0x03, 0x00, 0x49, 0x49, 0x09, 0x78, 0xce, 0xd7, 0x63, 0xf7, 0x00, 0x00, 0x00, 0x00, 0x49,
        0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82};

    cooker::ImageRgba image;
    SOL_CHECK(cooker::decodePng(kPng, sizeof(kPng), image));
    SOL_CHECK(image.width == 2 && image.height == 2);
    SOL_CHECK(image.pixels.size() == 16);

    const std::uint8_t* p = image.pixels.data();
    SOL_CHECK(p[0] == 255 && p[1] == 0 && p[2] == 0 && p[3] == 255);     // red
    SOL_CHECK(p[4] == 0 && p[5] == 255 && p[6] == 0 && p[7] == 255);     // green
    SOL_CHECK(p[8] == 0 && p[9] == 0 && p[10] == 255 && p[11] == 255);   // blue
    SOL_CHECK(p[12] == 255 && p[13] == 255 && p[14] == 255 && p[15] == 128); // white, half alpha
}

SOL_TEST(pngRejectsGarbage)
{
    cooker::ImageRgba image;
    const std::uint8_t junk[64] = {1, 2, 3};
    SOL_CHECK(!cooker::decodePng(junk, sizeof(junk), image));
}

SOL_TEST(bc1EncodesSolidBlockExactly)
{
    cooker::ImageRgba image;
    image.width = 4;
    image.height = 4;
    image.pixels.assign(64, 0);
    for (std::size_t i = 0; i < 16; ++i) {
        image.pixels[i * 4 + 0] = 255; // pure red
        image.pixels[i * 4 + 3] = 255;
    }

    const std::vector<std::uint8_t> blocks = cooker::encodeBc1(image);
    SOL_CHECK(blocks.size() == 8);
    // Both endpoints equal pure red in RGB565 (0xF800); all indices select c0.
    SOL_CHECK(blocks[0] == 0x00 && blocks[1] == 0xF8);
    SOL_CHECK(blocks[2] == 0x00 && blocks[3] == 0xF8);
    SOL_CHECK(blocks[4] == 0 && blocks[5] == 0 && blocks[6] == 0 && blocks[7] == 0);
}

SOL_TEST(bc1OutputSizeMatchesBlockCount)
{
    cooker::ImageRgba image;
    image.width = 6; // 2 blocks wide (rounded up)
    image.height = 10; // 3 blocks tall
    image.pixels.assign(static_cast<std::size_t>(image.width) * image.height * 4, 200);
    SOL_CHECK(cooker::encodeBc1(image).size() == 2u * 3u * 8u);
}

SOL_TEST(downsampleHalfAverages)
{
    cooker::ImageRgba image;
    image.width = 2;
    image.height = 2;
    image.pixels = {0, 0, 0, 255, 100, 0, 0, 255, 0, 200, 0, 255, 0, 0, 100, 255};
    const cooker::ImageRgba half = cooker::downsampleHalf(image);
    SOL_CHECK(half.width == 1 && half.height == 1);
    SOL_CHECK(half.pixels[0] == 25 && half.pixels[1] == 50 && half.pixels[2] == 25 &&
              half.pixels[3] == 255);
}

SOL_TEST(gltfImportsTriangleWithNodeTransform)
{
    // Triangle at (0,0,0) (1,0,0) (0,1,0), u16 indices, node translated +10 X.
    const char* gltf = R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "translation": [10, 0, 0]}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1}]}],
        "buffers": [{"byteLength": 42, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_triangle.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), gltf, std::strlen(gltf)));

    assets::MeshData mesh;
    SOL_CHECK(cooker::importGltf(path.c_str(), mesh));
    SOL_CHECK(mesh.vertices.size() == 3);
    SOL_CHECK(mesh.indices.size() == 3);
    SOL_CHECK(mesh.indices[0] == 0 && mesh.indices[1] == 1 && mesh.indices[2] == 2);
    // Node translation baked into positions.
    SOL_CHECK(mesh.vertices[0].position[0] == 10.0f);
    SOL_CHECK(mesh.vertices[1].position[0] == 11.0f);
    SOL_CHECK(mesh.vertices[2].position[1] == 1.0f);

    std::remove(path.c_str());
}

// --- sound (Phase 8t) ---

namespace {

void wavAppendTag(std::vector<std::uint8_t>& out, const char* tag)
{
    out.insert(out.end(), tag, tag + 4);
}

void wavAppendU32(std::vector<std::uint8_t>& out, std::uint32_t value)
{
    for (int shift = 0; shift < 32; shift += 8) {
        out.push_back(static_cast<std::uint8_t>((value >> shift) & 0xFFu));
    }
}

void wavAppendU16(std::vector<std::uint8_t>& out, std::uint16_t value)
{
    out.push_back(static_cast<std::uint8_t>(value & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 8) & 0xFFu));
}

// One fmt chunk and one data chunk, optionally with a LIST chunk wedged
// between them: real writers emit those, and the importer walks chunks rather
// than assuming an order precisely so they do not break it.
std::vector<std::uint8_t> buildWav(std::uint16_t format, std::uint16_t channels,
                                   std::uint32_t sampleRate, std::uint16_t bits,
                                   const std::vector<std::uint8_t>& payload,
                                   bool withListChunk = false)
{
    std::vector<std::uint8_t> body;
    wavAppendTag(body, "fmt ");
    wavAppendU32(body, 16);
    wavAppendU16(body, format);
    wavAppendU16(body, channels);
    wavAppendU32(body, sampleRate);
    wavAppendU32(body, sampleRate * channels * (bits / 8u));
    wavAppendU16(body, static_cast<std::uint16_t>(channels * (bits / 8u)));
    wavAppendU16(body, bits);

    if (withListChunk) {
        wavAppendTag(body, "LIST");
        wavAppendU32(body, 5); // odd, so the reader must honor the pad byte
        const char* info = "INFOx";
        body.insert(body.end(), info, info + 5);
        body.push_back(0);
    }

    wavAppendTag(body, "data");
    wavAppendU32(body, static_cast<std::uint32_t>(payload.size()));
    body.insert(body.end(), payload.begin(), payload.end());

    std::vector<std::uint8_t> file;
    wavAppendTag(file, "RIFF");
    wavAppendU32(file, static_cast<std::uint32_t>(body.size() + 4));
    wavAppendTag(file, "WAVE");
    file.insert(file.end(), body.begin(), body.end());
    return file;
}

std::vector<std::uint8_t> pcm16Payload(const std::vector<std::int16_t>& samples)
{
    std::vector<std::uint8_t> bytes;
    for (std::int16_t sample : samples) {
        wavAppendU16(bytes, static_cast<std::uint16_t>(sample));
    }
    return bytes;
}

} // namespace

SOL_TEST(wavImportsPcm16Stereo)
{
    const std::vector<std::int16_t> samples = {0, 1000, -1000, 32767, -32768, 5};
    const std::vector<std::uint8_t> file = buildWav(1, 2, 44100, 16, pcm16Payload(samples));

    assets::SoundData sound;
    SOL_CHECK(cooker::importWav(file.data(), file.size(), sound));
    SOL_CHECK(sound.sampleRate == 44100);
    SOL_CHECK(sound.channelCount == 2);
    SOL_CHECK(sound.frameCount() == 3); // six samples, two channels
    SOL_CHECK(sound.samples == samples);
}

SOL_TEST(wavWalksPastUnknownChunks)
{
    const std::vector<std::int16_t> samples = {7, -7};
    const std::vector<std::uint8_t> file = buildWav(1, 1, 22050, 16, pcm16Payload(samples), true);

    assets::SoundData sound;
    SOL_CHECK(cooker::importWav(file.data(), file.size(), sound));
    SOL_CHECK(sound.sampleRate == 22050);
    SOL_CHECK(sound.frameCount() == 2);
    SOL_CHECK(sound.samples == samples);
}

SOL_TEST(wavNormalizesSampleWidthsToInt16)
{
    // 8-bit is unsigned with a midpoint of 128, so silence is 0x80.
    const std::vector<std::uint8_t> eightBit = {128, 255, 0};
    const std::vector<std::uint8_t> eightBitFile = buildWav(1, 1, 8000, 8, eightBit);
    assets::SoundData fromEight;
    SOL_CHECK(cooker::importWav(eightBitFile.data(), eightBitFile.size(), fromEight));
    SOL_CHECK(fromEight.samples.size() == 3);
    SOL_CHECK(fromEight.samples[0] == 0);
    SOL_CHECK(fromEight.samples[1] == 32512);  // (255 - 128) << 8
    SOL_CHECK(fromEight.samples[2] == -32768); // (0 - 128) << 8

    // 32-bit float is normalized [-1, 1] and clamps rather than wrapping.
    const float floats[] = {0.0f, 1.0f, -1.0f, 2.0f};
    std::vector<std::uint8_t> floatPayload(sizeof(floats));
    std::memcpy(floatPayload.data(), floats, sizeof(floats));
    const std::vector<std::uint8_t> floatFile = buildWav(3, 1, 48000, 32, floatPayload);
    assets::SoundData fromFloat;
    SOL_CHECK(cooker::importWav(floatFile.data(), floatFile.size(), fromFloat));
    SOL_CHECK(fromFloat.samples.size() == 4);
    SOL_CHECK(fromFloat.samples[0] == 0);
    SOL_CHECK(fromFloat.samples[1] == 32767);
    SOL_CHECK(fromFloat.samples[2] == -32767);
    SOL_CHECK(fromFloat.samples[3] == 32767); // clamped, not wrapped
}

SOL_TEST(wavRejectsWhatItCannotPlay)
{
    const std::vector<std::uint8_t> payload = pcm16Payload({1, 2});
    assets::SoundData sound;

    std::vector<std::uint8_t> notRiff = buildWav(1, 1, 44100, 16, payload);
    notRiff[0] = 'X';
    SOL_CHECK(!cooker::importWav(notRiff.data(), notRiff.size(), sound));

    // A compressed format (ADPCM) is refused rather than read as PCM.
    const std::vector<std::uint8_t> adpcm = buildWav(2, 1, 44100, 16, payload);
    SOL_CHECK(!cooker::importWav(adpcm.data(), adpcm.size(), sound));

    // More channels than the mixer has a policy for.
    const std::vector<std::uint8_t> surround = buildWav(1, 6, 44100, 16, payload);
    SOL_CHECK(!cooker::importWav(surround.data(), surround.size(), sound));

    // A chunk header claiming more bytes than the file holds.
    std::vector<std::uint8_t> truncated = buildWav(1, 1, 44100, 16, payload);
    truncated.resize(truncated.size() - 2);
    SOL_CHECK(!cooker::importWav(truncated.data(), truncated.size(), sound));

    // fmt but no data.
    std::vector<std::uint8_t> headerOnly = buildWav(1, 1, 44100, 16, {});
    headerOnly.resize(20 + 16); // RIFF/WAVE + the fmt chunk, nothing after
    SOL_CHECK(!cooker::importWav(headerOnly.data(), headerOnly.size(), sound));
}

SOL_TEST(oggRejectsGarbageWithoutCrashing)
{
    assets::SoundData sound;
    const std::uint8_t notOgg[] = {'n', 'o', 't', ' ', 'a', 'n', ' ', 'o', 'g', 'g'};
    SOL_CHECK(!cooker::importOgg(notOgg, sizeof(notOgg), sound));
    SOL_CHECK(!cooker::importOgg(notOgg, 0, sound));

    // A valid capture pattern with nothing behind it: the decoder must fail
    // rather than read past the buffer.
    const std::uint8_t oggHeaderOnly[] = {'O', 'g', 'g', 'S', 0, 2, 0, 0};
    SOL_CHECK(!cooker::importOgg(oggHeaderOnly, sizeof(oggHeaderOnly), sound));
}

SOL_TEST(soundRoundTripsThroughTheCookedFormat)
{
    assets::SoundData source;
    source.sampleRate = 44100;
    source.channelCount = 1;
    source.samples = {0, 128, -128, 32767, -32768};

    const std::vector<std::uint8_t> encoded = cooker::encodeSound(source);
    SOL_CHECK(encoded.size() ==
              sizeof(assets::SoundFileHeader) + source.samples.size() * sizeof(std::int16_t));

    const std::string path = std::string(platform::executableDirectory()) + "test_roundtrip.saud";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), encoded.data(), encoded.size()));

    assets::SoundData loaded;
    SOL_CHECK(assets::loadSound(path.c_str(), loaded));
    SOL_CHECK(loaded.sampleRate == source.sampleRate);
    SOL_CHECK(loaded.channelCount == source.channelCount);
    SOL_CHECK(loaded.frameCount() == 5);
    SOL_CHECK(loaded.samples == source.samples);

    // A truncated payload is a size mismatch, not a short read.
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), encoded.data(), encoded.size() - 2));
    assets::SoundData shortLoad;
    SOL_CHECK(!assets::loadSound(path.c_str(), shortLoad));

    std::remove(path.c_str());
}
