#include "bc1.hpp"
#include "cook.hpp"
#include "gltf.hpp"
#include "mesh.hpp"
#include "outputs.hpp"
#include "png.hpp"
#include "sound.hpp"
#include "texture.hpp"

#include "sol/assets/asset_loader.hpp"
#include "sol/assets/formats.hpp"
#include "sol/assets/sound_doc.hpp"
#include "sol/platform/file_io.hpp"
#include "sol/test/test.hpp"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace sol;

SOL_TEST(base64DecodesKnownVectors)
{
    std::vector<std::uint8_t> out;
    SOL_CHECK(cooker::decodeBase64("aGVsbG8=", 8, out));
    SOL_CHECK(out.size() == 5 && std::memcmp(out.data(), "hello", 5) == 0);
    SOL_CHECK(cooker::decodeBase64("", 0, out) && out.empty());
    SOL_CHECK(!cooker::decodeBase64("a!b", 3, out));
}

// 2x2 RGBA PNG generated by System.Drawing:
// (0,0) red, (1,0) green, (0,1) blue, (1,1) white with alpha 128.
//
// ⚑⚑ FILE-SCOPE SINCE STAGE U3, WHICH NEEDS IT TWICE OVER: once as the thing
// `decodePng` reads, and once as a whole file EMBEDDED IN A GLB, where the
// assertion is that the importer hands back these bytes and not merely an image
// equal to them. Shared rather than re-typed for the reason U2 gave when it
// borrowed this same array: a PNG written by a test is a second implementation
// of a format, and a fixture only this repo's decoder accepts is the exact
// failure these tests exist to catch. This one came out of another program.
static const std::uint8_t kPng2x2[] = {
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02, 0x08, 0x06, 0x00, 0x00, 0x00, 0x72, 0xb6, 0x0d,
    0x24, 0x00, 0x00, 0x00, 0x01, 0x73, 0x52, 0x47, 0x42, 0x00, 0xae, 0xce, 0x1c, 0xe9, 0x00, 0x00,
    0x00, 0x04, 0x67, 0x41, 0x4d, 0x41, 0x00, 0x00, 0xb1, 0x8f, 0x0b, 0xfc, 0x61, 0x05, 0x00, 0x00,
    0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00, 0x0e, 0xc3, 0x00, 0x00, 0x0e, 0xc3, 0x01, 0xc7,
    0x6f, 0xa8, 0x64, 0x00, 0x00, 0x00, 0x14, 0x49, 0x44, 0x41, 0x54, 0x18, 0x57, 0x63, 0xf8, 0xcf,
    0xc0, 0xf0, 0x1f, 0x0c, 0x19, 0x18, 0xfe, 0x83, 0x40, 0x03, 0x00, 0x49, 0x49, 0x09, 0x78, 0xce,
    0xd7, 0x63, 0xf7, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82};

SOL_TEST(pngDecodesRgba2x2)
{
    cooker::ImageRgba image;
    SOL_CHECK(cooker::decodePng(kPng2x2, sizeof(kPng2x2), image));
    SOL_CHECK(image.width == 2 && image.height == 2);
    SOL_CHECK(image.pixels.size() == 16);

    const std::uint8_t* p = image.pixels.data();
    SOL_CHECK(p[0] == 255 && p[1] == 0 && p[2] == 0 && p[3] == 255);         // red
    SOL_CHECK(p[4] == 0 && p[5] == 255 && p[6] == 0 && p[7] == 255);         // green
    SOL_CHECK(p[8] == 0 && p[9] == 0 && p[10] == 255 && p[11] == 255);       // blue
    SOL_CHECK(p[12] == 255 && p[13] == 255 && p[14] == 255 && p[15] == 128); // white, half alpha
}

SOL_TEST(pngRejectsGarbage)
{
    cooker::ImageRgba image;
    const std::uint8_t junk[64] = {1, 2, 3};
    SOL_CHECK(!cooker::decodePng(junk, sizeof(junk), image));
}

SOL_TEST(bc1EncodesSolidBlockExactly)
{
    cooker::ImageRgba image;
    image.width = 4;
    image.height = 4;
    image.pixels.assign(64, 0);
    for (std::size_t i = 0; i < 16; ++i) {
        image.pixels[i * 4 + 0] = 255; // pure red
        image.pixels[i * 4 + 3] = 255;
    }

    const std::vector<std::uint8_t> blocks = cooker::encodeBc1(image);
    SOL_CHECK(blocks.size() == 8);
    // Both endpoints equal pure red in RGB565 (0xF800); all indices select c0.
    SOL_CHECK(blocks[0] == 0x00 && blocks[1] == 0xF8);
    SOL_CHECK(blocks[2] == 0x00 && blocks[3] == 0xF8);
    SOL_CHECK(blocks[4] == 0 && blocks[5] == 0 && blocks[6] == 0 && blocks[7] == 0);
}

SOL_TEST(bc1OutputSizeMatchesBlockCount)
{
    cooker::ImageRgba image;
    image.width = 6;   // 2 blocks wide (rounded up)
    image.height = 10; // 3 blocks tall
    image.pixels.assign(static_cast<std::size_t>(image.width) * image.height * 4, 200);
    SOL_CHECK(cooker::encodeBc1(image).size() == 2u * 3u * 8u);
}

SOL_TEST(downsampleHalfAverages)
{
    cooker::ImageRgba image;
    image.width = 2;
    image.height = 2;
    image.pixels = {0, 0, 0, 255, 100, 0, 0, 255, 0, 200, 0, 255, 0, 0, 100, 255};
    const cooker::ImageRgba half = cooker::downsampleHalf(image);
    SOL_CHECK(half.width == 1 && half.height == 1);
    SOL_CHECK(half.pixels[0] == 25 && half.pixels[1] == 50 && half.pixels[2] == 25 && half.pixels[3] == 255);
}

SOL_TEST(gltfImportsTriangleWithNodeTransform)
{
    // Triangle at (0,0,0) (1,0,0) (0,1,0), u16 indices, node translated +10 X.
    const char* gltf = R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "translation": [10, 0, 0]}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1}]}],
        "buffers": [{"byteLength": 42, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_triangle.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), gltf, std::strlen(gltf)));

    assets::MeshData mesh;
    SOL_CHECK(cooker::importGltf(path.c_str(), mesh));
    SOL_CHECK(mesh.vertices.size() == 3);
    SOL_CHECK(mesh.indices.size() == 3);
    SOL_CHECK(mesh.indices[0] == 0 && mesh.indices[1] == 1 && mesh.indices[2] == 2);
    // Node translation baked into positions.
    SOL_CHECK(mesh.vertices[0].position[0] == 10.0f);
    SOL_CHECK(mesh.vertices[1].position[0] == 11.0f);
    SOL_CHECK(mesh.vertices[2].position[1] == 1.0f);

    std::remove(path.c_str());
}

// ⚑ STAGE P's CHANNEL. `extras` is where glTF lets an exporter put its own
// data, and the Send-to-Forge addon stamps the Blender object's uid there -
// which is the only field in the file that survives a rename. Verified against
// real Blender 5.2 before this was built: an object custom property comes out
// as `extras: {"sol_forge_uid": ...}` on the NODE, beside the name.
//
// The absent and wrong-typed cases are here because they are normal: every
// glTF written by anything else, and everything exported before stage P, has no
// extras at all, and an empty origin must read as "unidentified" rather than
// as a failure.
SOL_TEST(aNodesOriginIdIsReadFromExtrasAndIsEmptyWhenThereIsNone)
{
    const char* gltf = R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0, 1, 2]}],
        "nodes": [
            {"mesh": 0, "name": "Hull", "extras": {"sol_forge_uid": "abc123"}},
            {"mesh": 0, "name": "Plain"},
            {"mesh": 0, "name": "Odd", "extras": {"sol_forge_uid": 7}}
        ],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1}]}],
        "buffers": [{"byteLength": 42, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_extras.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), gltf, std::strlen(gltf)));

    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(cooker::importGltfParts(path.c_str(), parts));
    SOL_REQUIRE(parts.size() == 3);

    SOL_CHECK(parts[0].name == "Hull" && parts[0].originId == "abc123");
    // No extras at all: every file written by anything but this addon.
    SOL_CHECK(parts[1].name == "Plain" && parts[1].originId.empty());
    // Somebody else's key that happens to collide - not a string, so not ours.
    SOL_CHECK(parts[2].name == "Odd" && parts[2].originId.empty());

    std::remove(path.c_str());
}

// ⚑⚑ THE INPUT HAD TO BE BUILT, WHICH IS THE POINT: NOTHING COMMITTED CAN TRIP
// THIS. Every mesh in `assets/meshes/` is a `.forge`, and the generator that
// wrote the last `.gltf` never scaled a node - so the importer carried a normal
// rule that is wrong under non-uniform scale for as long as it has existed, with
// a comment saying so, and no asset in the repo could tell. Stage L's Blender
// bridge is what makes it reachable: `S` `X` `2` on an object is one keystroke
// and the exporter writes it into the node.
//
// ⚑ The case is chosen so the two rules cannot be confused: a 45 degree normal
// under a 2x stretch in X gives (0.4472, 0.8944) transformed correctly and
// (0.8944, 0.4472) transformed by the node matrix - THE SAME TWO NUMBERS,
// EXACTLY SWAPPED. A tolerance cannot straddle them and a sign error cannot
// fake one.
SOL_TEST(gltfNormalsSurviveANodeThatScalesUnevenly)
{
    // A triangle in the plane whose normal is (1,1,0)/sqrt(2), under scale
    // [2,1,1]. Stretching X flattens the surface towards the X axis, so the
    // normal must rotate TOWARDS Y - the opposite of what scaling it does.
    const char* gltf = R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "scale": [2, 1, 1]}],
        "meshes": [{"primitives": [
            {"attributes": {"POSITION": 0, "NORMAL": 1}, "indices": 2}]}],
        "buffers": [{"byteLength": 78, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAgL8AAAAAAAAAAAAAAAAAAIA/8wQ1P/MENT8AAAAA8wQ1P/MENT8AAAAA8wQ1P/MENT8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 36},
            {"buffer": 0, "byteOffset": 72, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 2, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_skewnormal.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), gltf, std::strlen(gltf)));

    assets::MeshData mesh;
    SOL_CHECK(cooker::importGltf(path.c_str(), mesh));
    SOL_CHECK(mesh.vertices.size() == 3);

    for (const assets::MeshVertex& vertex : mesh.vertices) {
        SOL_CHECK(std::fabs(vertex.normal[0] - 0.4472136f) < 1e-4f);
        SOL_CHECK(std::fabs(vertex.normal[1] - 0.8944272f) < 1e-4f);
        SOL_CHECK(std::fabs(vertex.normal[2]) < 1e-6f);
        // Still unit length, which scaling by the node matrix would also
        // satisfy - so it is the ordering above that carries the assertion.
        const float length =
            std::sqrt(vertex.normal[0] * vertex.normal[0] + vertex.normal[1] * vertex.normal[1] +
                      vertex.normal[2] * vertex.normal[2]);
        SOL_CHECK(std::fabs(length - 1.0f) < 1e-5f);
    }

    // The positions are stretched by the node matrix itself, unchanged by any
    // of this: a normal rule that also moved a vertex would be a different bug.
    SOL_CHECK(std::fabs(mesh.vertices[1].position[0] - 2.0f) < 1e-6f);
    SOL_CHECK(std::fabs(mesh.vertices[1].position[1] + 1.0f) < 1e-6f);

    std::remove(path.c_str());
}

// --- the stray sweep -------------------------------------------------------

namespace {

[[nodiscard]] bool contains(const std::vector<std::string>& names, const char* name)
{
    for (const std::string& candidate : names) {
        if (candidate == name) {
            return true;
        }
    }
    return false;
}

} // namespace

// ⚑⚑ A LIVE MESH CLAIMS ITS WHOLE LOD SIBLING RANGE, NOT JUST THE LEVELS IT
// HAPPENS TO HAVE. How many levels an asset generates is not known until it
// cooks, and a cook is SKIPPED when the output is up to date - so a sweep that
// only claimed the levels present would delete a live asset's LODs on the first
// incremental build. Trimming a chain that legitimately got SHORTER stays
// `writeMeshLevels`'s job, where the new length is actually known.
SOL_TEST(aLiveMeshClaimsEveryLevelItCouldEverHave)
{
    const std::vector<std::string> expected =
        cooker::expectedOutputNames({"out/station.smesh", "out/hull.stex"});

    SOL_CHECK(contains(expected, "station.smesh"));
    SOL_CHECK(contains(expected, "hull.stex"));
    for (std::uint32_t level = 1; level <= cooker::kMaxMeshLevels; ++level) {
        SOL_CHECK(contains(expected, ("station.lod" + std::to_string(level) + ".smesh").c_str()));
    }
    // A texture has no sibling range, so it must not invent one.
    SOL_CHECK(!contains(expected, "hull.lod1.stex"));

    // ⚑ Names, not paths: the output directory is flat, and the cooker builds
    // its paths from an argv string whose separators do not survive a round
    // trip through `listFiles`.
    SOL_CHECK(!contains(expected, "out/station.smesh"));
}

// ⚑⚑ THE CASE THE SWEEP EXISTS FOR: a deleted source. The cook walks SOURCES,
// so nothing ever visits an asset that is gone - its `.smesh` AND every level
// beside it would otherwise sit in the cooked directory forever, listed by the
// Forge as rows that open and never edit.
SOL_TEST(anOutputWhoseSourceIsGoneIsAStrayAndSoAreItsLevels)
{
    const std::vector<std::string> expected = cooker::expectedOutputNames({"out/station.smesh"});
    const std::vector<std::string> present = {
        "out/station.smesh",
        "out/station.lod1.smesh",
        "out/station.lod2.smesh",
        "out/deleted.smesh",
        "out/deleted.lod1.smesh",
    };

    const std::vector<std::string> strays = cooker::strayOutputNames(expected, present);
    SOL_REQUIRE(strays.size() == 2);
    SOL_CHECK(contains(strays, "out/deleted.smesh"));
    SOL_CHECK(contains(strays, "out/deleted.lod1.smesh"));

    // ⚑ And the negative half, which is the one that matters: the live asset's
    // levels survive. A sweep that got this wrong would delete a real LOD chain
    // on every build, and the damage would only show up at distance.
    SOL_CHECK(!contains(strays, "out/station.smesh"));
    SOL_CHECK(!contains(strays, "out/station.lod1.smesh"));
    SOL_CHECK(!contains(strays, "out/station.lod2.smesh"));
}

// ⚑ The output directory is not ours alone. A sweep that deleted whatever it
// did not recognise is one nobody could safely add a format beside.
SOL_TEST(theSweepTouchesOnlyTheFourFormatsTheCookerWrites)
{
    const std::vector<std::string> expected = cooker::expectedOutputNames({"out/ship.smesh"});
    const std::vector<std::string> present = {
        "out/orphan.smesh",
        "out/orphan.stex",
        "out/orphan.saud",
        "out/orphan.sfont",
        "out/mesh.frag.spv",
        "out/notes.txt",
        "out/imgui.ini",
        "out/no_extension",
    };

    const std::vector<std::string> strays = cooker::strayOutputNames(expected, present);
    SOL_REQUIRE(strays.size() == 4);
    SOL_CHECK(contains(strays, "out/orphan.smesh"));
    SOL_CHECK(contains(strays, "out/orphan.stex"));
    SOL_CHECK(contains(strays, "out/orphan.saud"));
    SOL_CHECK(contains(strays, "out/orphan.sfont"));
    // The compiled shaders live beside the cooked assets and are not ours.
    SOL_CHECK(!contains(strays, "out/mesh.frag.spv"));
    SOL_CHECK(!contains(strays, "out/notes.txt"));
    SOL_CHECK(!contains(strays, "out/imgui.ini"));
    SOL_CHECK(!contains(strays, "out/no_extension"));
}

// ⚑⚑ THE TYPO CASE, AND IT IS THE ONE THAT WOULD HURT MOST. With no jobs every
// cooked file is unclaimed, so the rule below is correct and catastrophic at
// the same time - which is exactly why `main.cpp` refuses to ACT on it and logs
// instead. Pinned here so the day someone "simplifies" that guard away, the
// reason it exists is written down beside the behaviour it permits.
SOL_TEST(withNoJobsEveryCookedFileLooksLikeAStrayWhichIsWhyTheCallerRefuses)
{
    const std::vector<std::string> expected = cooker::expectedOutputNames({});
    SOL_CHECK(expected.empty());

    const std::vector<std::string> present = {"out/station.smesh", "out/hull.stex"};
    SOL_CHECK(cooker::strayOutputNames(expected, present).size() == 2);
}

// --- sound (Phase 8t) ---

namespace {

void wavAppendTag(std::vector<std::uint8_t>& out, const char* tag)
{
    out.insert(out.end(), tag, tag + 4);
}

void wavAppendU32(std::vector<std::uint8_t>& out, std::uint32_t value)
{
    for (int shift = 0; shift < 32; shift += 8) {
        out.push_back(static_cast<std::uint8_t>((value >> shift) & 0xFFu));
    }
}

void wavAppendU16(std::vector<std::uint8_t>& out, std::uint16_t value)
{
    out.push_back(static_cast<std::uint8_t>(value & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 8) & 0xFFu));
}

// One fmt chunk and one data chunk, optionally with a LIST chunk wedged
// between them: real writers emit those, and the importer walks chunks rather
// than assuming an order precisely so they do not break it.
std::vector<std::uint8_t> buildWav(std::uint16_t format,
                                   std::uint16_t channels,
                                   std::uint32_t sampleRate,
                                   std::uint16_t bits,
                                   const std::vector<std::uint8_t>& payload,
                                   bool withListChunk = false)
{
    std::vector<std::uint8_t> body;
    wavAppendTag(body, "fmt ");
    wavAppendU32(body, 16);
    wavAppendU16(body, format);
    wavAppendU16(body, channels);
    wavAppendU32(body, sampleRate);
    wavAppendU32(body, sampleRate * channels * (bits / 8u));
    wavAppendU16(body, static_cast<std::uint16_t>(channels * (bits / 8u)));
    wavAppendU16(body, bits);

    if (withListChunk) {
        wavAppendTag(body, "LIST");
        wavAppendU32(body, 5); // odd, so the reader must honor the pad byte
        const char* info = "INFOx";
        body.insert(body.end(), info, info + 5);
        body.push_back(0);
    }

    wavAppendTag(body, "data");
    wavAppendU32(body, static_cast<std::uint32_t>(payload.size()));
    body.insert(body.end(), payload.begin(), payload.end());

    std::vector<std::uint8_t> file;
    wavAppendTag(file, "RIFF");
    wavAppendU32(file, static_cast<std::uint32_t>(body.size() + 4));
    wavAppendTag(file, "WAVE");
    file.insert(file.end(), body.begin(), body.end());
    return file;
}

std::vector<std::uint8_t> pcm16Payload(const std::vector<std::int16_t>& samples)
{
    std::vector<std::uint8_t> bytes;
    for (std::int16_t sample : samples) {
        wavAppendU16(bytes, static_cast<std::uint16_t>(sample));
    }
    return bytes;
}

} // namespace

SOL_TEST(wavImportsPcm16Stereo)
{
    const std::vector<std::int16_t> samples = {0, 1000, -1000, 32767, -32768, 5};
    const std::vector<std::uint8_t> file = buildWav(1, 2, 44100, 16, pcm16Payload(samples));

    assets::SoundData sound;
    SOL_CHECK(cooker::importWav(file.data(), file.size(), sound));
    SOL_CHECK(sound.sampleRate == 44100);
    SOL_CHECK(sound.channelCount == 2);
    SOL_CHECK(sound.frameCount() == 3); // six samples, two channels
    SOL_CHECK(sound.samples == samples);
}

SOL_TEST(wavWalksPastUnknownChunks)
{
    const std::vector<std::int16_t> samples = {7, -7};
    const std::vector<std::uint8_t> file = buildWav(1, 1, 22050, 16, pcm16Payload(samples), true);

    assets::SoundData sound;
    SOL_CHECK(cooker::importWav(file.data(), file.size(), sound));
    SOL_CHECK(sound.sampleRate == 22050);
    SOL_CHECK(sound.frameCount() == 2);
    SOL_CHECK(sound.samples == samples);
}

SOL_TEST(wavNormalizesSampleWidthsToInt16)
{
    // 8-bit is unsigned with a midpoint of 128, so silence is 0x80.
    const std::vector<std::uint8_t> eightBit = {128, 255, 0};
    const std::vector<std::uint8_t> eightBitFile = buildWav(1, 1, 8000, 8, eightBit);
    assets::SoundData fromEight;
    SOL_CHECK(cooker::importWav(eightBitFile.data(), eightBitFile.size(), fromEight));
    SOL_CHECK(fromEight.samples.size() == 3);
    SOL_CHECK(fromEight.samples[0] == 0);
    SOL_CHECK(fromEight.samples[1] == 32512);  // (255 - 128) << 8
    SOL_CHECK(fromEight.samples[2] == -32768); // (0 - 128) << 8

    // 32-bit float is normalized [-1, 1] and clamps rather than wrapping.
    const float floats[] = {0.0f, 1.0f, -1.0f, 2.0f};
    std::vector<std::uint8_t> floatPayload(sizeof(floats));
    std::memcpy(floatPayload.data(), floats, sizeof(floats));
    const std::vector<std::uint8_t> floatFile = buildWav(3, 1, 48000, 32, floatPayload);
    assets::SoundData fromFloat;
    SOL_CHECK(cooker::importWav(floatFile.data(), floatFile.size(), fromFloat));
    SOL_CHECK(fromFloat.samples.size() == 4);
    SOL_CHECK(fromFloat.samples[0] == 0);
    SOL_CHECK(fromFloat.samples[1] == 32767);
    SOL_CHECK(fromFloat.samples[2] == -32767);
    SOL_CHECK(fromFloat.samples[3] == 32767); // clamped, not wrapped
}

SOL_TEST(wavRejectsWhatItCannotPlay)
{
    const std::vector<std::uint8_t> payload = pcm16Payload({1, 2});
    assets::SoundData sound;

    std::vector<std::uint8_t> notRiff = buildWav(1, 1, 44100, 16, payload);
    notRiff[0] = 'X';
    SOL_CHECK(!cooker::importWav(notRiff.data(), notRiff.size(), sound));

    // A compressed format (ADPCM) is refused rather than read as PCM.
    const std::vector<std::uint8_t> adpcm = buildWav(2, 1, 44100, 16, payload);
    SOL_CHECK(!cooker::importWav(adpcm.data(), adpcm.size(), sound));

    // More channels than the mixer has a policy for.
    const std::vector<std::uint8_t> surround = buildWav(1, 6, 44100, 16, payload);
    SOL_CHECK(!cooker::importWav(surround.data(), surround.size(), sound));

    // A chunk header claiming more bytes than the file holds.
    std::vector<std::uint8_t> truncated = buildWav(1, 1, 44100, 16, payload);
    truncated.resize(truncated.size() - 2);
    SOL_CHECK(!cooker::importWav(truncated.data(), truncated.size(), sound));

    // fmt but no data.
    std::vector<std::uint8_t> headerOnly = buildWav(1, 1, 44100, 16, {});
    headerOnly.resize(20 + 16); // RIFF/WAVE + the fmt chunk, nothing after
    SOL_CHECK(!cooker::importWav(headerOnly.data(), headerOnly.size(), sound));
}

SOL_TEST(oggRejectsGarbageWithoutCrashing)
{
    assets::SoundData sound;
    const std::uint8_t notOgg[] = {'n', 'o', 't', ' ', 'a', 'n', ' ', 'o', 'g', 'g'};
    SOL_CHECK(!cooker::importOgg(notOgg, sizeof(notOgg), sound));
    SOL_CHECK(!cooker::importOgg(notOgg, 0, sound));

    // A valid capture pattern with nothing behind it: the decoder must fail
    // rather than read past the buffer.
    const std::uint8_t oggHeaderOnly[] = {'O', 'g', 'g', 'S', 0, 2, 0, 0};
    SOL_CHECK(!cooker::importOgg(oggHeaderOnly, sizeof(oggHeaderOnly), sound));
}

SOL_TEST(soundRoundTripsThroughTheCookedFormat)
{
    assets::SoundData source;
    source.sampleRate = 44100;
    source.channelCount = 1;
    source.samples = {0, 128, -128, 32767, -32768};

    const std::vector<std::uint8_t> encoded = cooker::encodeSound(source);
    SOL_CHECK(encoded.size() ==
              sizeof(assets::SoundFileHeader) + source.samples.size() * sizeof(std::int16_t));

    const std::string path = std::string(platform::executableDirectory()) + "test_roundtrip.saud";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), encoded.data(), encoded.size()));

    assets::SoundData loaded;
    SOL_CHECK(assets::loadSound(path.c_str(), loaded));
    SOL_CHECK(loaded.sampleRate == source.sampleRate);
    SOL_CHECK(loaded.channelCount == source.channelCount);
    SOL_CHECK(loaded.frameCount() == 5);
    SOL_CHECK(loaded.samples == source.samples);

    // A truncated payload is a size mismatch, not a short read.
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), encoded.data(), encoded.size() - 2));
    assets::SoundData shortLoad;
    SOL_CHECK(!assets::loadSound(path.c_str(), shortLoad));

    std::remove(path.c_str());
}

SOL_TEST(base64EncodesKnownVectors)
{
    SOL_CHECK(cooker::encodeBase64(reinterpret_cast<const std::uint8_t*>("hello"), 5) == "aGVsbG8=");
    SOL_CHECK(cooker::encodeBase64(reinterpret_cast<const std::uint8_t*>("hi"), 2) == "aGk=");
    SOL_CHECK(cooker::encodeBase64(reinterpret_cast<const std::uint8_t*>("abc"), 3) == "YWJj");
    SOL_CHECK(cooker::encodeBase64(nullptr, 0).empty());
}

// ⚑ The export is only worth anything if another program can read it back, and
// the cheapest honest proof of that is this repo's own importer - which was
// written against files this exporter did not produce, so it is a real second
// opinion rather than a mirror.
SOL_TEST(gltfExportRoundTripsThroughTheImporter)
{
    assets::MeshData original;
    original.vertices = {
        {{0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},
        {{2.5f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},
        {{0.0f, 0.0f, -4.25f}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f}},
        {{-3.0f, 1.5f, 2.0f}, {0.0f, 0.0f, 1.0f}, {0.5f, 0.5f}},
    };
    original.indices = {0, 1, 2, 0, 2, 3};

    const std::string json = cooker::exportGltf(original, "probe");
    const std::string path = std::string(platform::executableDirectory()) + "test_export.gltf";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), json.data(), json.size()));

    assets::MeshData reimported;
    SOL_CHECK(cooker::importGltf(path.c_str(), reimported));
    SOL_REQUIRE(reimported.vertices.size() == original.vertices.size());
    SOL_CHECK(reimported.indices == original.indices);
    for (std::size_t i = 0; i < original.vertices.size(); ++i) {
        for (int axis = 0; axis < 3; ++axis) {
            SOL_CHECK(reimported.vertices[i].position[axis] == original.vertices[i].position[axis]);
            SOL_CHECK(reimported.vertices[i].normal[axis] == original.vertices[i].normal[axis]);
        }
        SOL_CHECK(reimported.vertices[i].uv[0] == original.vertices[i].uv[0]);
        SOL_CHECK(reimported.vertices[i].uv[1] == original.vertices[i].uv[1]);
    }

    // POSITION min/max are required by the spec, and a viewer that frames on
    // bounds reads them rather than the vertices.
    SOL_CHECK(json.find("\"min\":[-3,0,-4.25]") != std::string::npos);
    SOL_CHECK(json.find("\"max\":[2.5,1.5,2]") != std::string::npos);

    std::remove(path.c_str());
}

// ---------------------------------------------------------------------------
// The mesh cook. Reachable from here for the first time: until this slice
// `writeMesh` and every `cook*` lived in the cooker's `main.cpp`, outside the
// library this binary links, which is why the D checkpoint's "nothing compares
// the cooked .smesh against anything" survived three slices of being written
// down as still open.
// ---------------------------------------------------------------------------

// ⚑⚑ THE END-TO-END CLAIM, AND IT IS THE ONE NOTHING HAS EVER MADE: WHAT THE
// GAME LOADS IS WHAT THE AUTHOR BUILT. `encodeMesh` lives in `tools/cooker` and
// `assets::loadMesh` lives in `sol::assets` - two descriptions of one file
// format, in two modules, which is exactly the pair that bit at stage D when
// `cooker(.gltf)` and `cooker(.forge)` turned out never to have been the same
// bytes. Each half agreeing with itself proves nothing; this is the two halves
// agreeing with each other, over the real committed assets.
SOL_TEST(everyCommittedForgeSourceReachesTheGameAsTheMeshItsAuthorBuilt)
{
    const char* const names[] = {"cube", "gate", "ship", "station", "cockpit", "asteroid"};
    for (const char* name : names) {
        const std::string source = std::string(SOL_MESH_SOURCE_DIR) + "/" + name + ".forge";

        assets::MeshData built;
        std::string error;
        SOL_REQUIRE(cooker::importForgeMesh(source.c_str(), built, &error));
        SOL_CHECK(error.empty());

        const std::vector<std::uint8_t> bytes = cooker::encodeMesh(built);
        // Header, then vertices, then indices - nothing else, no padding.
        SOL_CHECK(bytes.size() == sizeof(assets::MeshFileHeader) +
                                      (built.vertices.size() * sizeof(assets::MeshVertex)) +
                                      (built.indices.size() * sizeof(std::uint32_t)));

        const std::string path =
            std::string(platform::executableDirectory()) + "test_cook_" + name + ".smesh";
        SOL_REQUIRE(platform::writeFileBytes(path.c_str(), bytes.data(), bytes.size()));

        // ⚑ Loaded through the RUNTIME's own loader, not a second reader
        // written for the test. A reader that agreed with this writer because
        // they were written together is the thing being ruled out.
        assets::MeshData loaded;
        SOL_REQUIRE(assets::loadMesh(path.c_str(), loaded));
        SOL_REQUIRE(loaded.vertices.size() == built.vertices.size());
        SOL_REQUIRE(loaded.indices.size() == built.indices.size());
        SOL_CHECK(std::memcmp(loaded.vertices.data(),
                              built.vertices.data(),
                              built.vertices.size() * sizeof(assets::MeshVertex)) == 0);
        SOL_CHECK(std::memcmp(loaded.indices.data(),
                              built.indices.data(),
                              built.indices.size() * sizeof(std::uint32_t)) == 0);

        std::remove(path.c_str());
    }
}

// ⚑ `encodeMesh` never SETS `magic` or `version` - it writes
// `MeshFileHeader header = {}` and leans on the struct's default member
// initialisers, while `loadMesh` validates both. That is correct today and was
// asserted by nothing, so an explicit constructor or a stray `= {0}` would ship
// files the game rejects while the cooker reported success on every one.
SOL_TEST(theCookedMeshHeaderCarriesTheMagicAndVersionTheLoaderDemands)
{
    assets::MeshData mesh;
    mesh.vertices = {{{0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},
                     {{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},
                     {{0.0f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f}}};
    mesh.indices = {0, 1, 2};

    const std::vector<std::uint8_t> bytes = cooker::encodeMesh(mesh);
    assets::MeshFileHeader header = {};
    SOL_REQUIRE(bytes.size() >= sizeof(header));
    std::memcpy(&header, bytes.data(), sizeof(header));
    SOL_CHECK(header.magic == assets::kMeshMagic);
    SOL_CHECK(header.version == assets::kFormatVersion);
    SOL_CHECK(header.vertexCount == 3);
    SOL_CHECK(header.indexCount == 3);
}

// The three ways a `.smesh` can be wrong, each refused rather than read past.
// A loader that accepted any of them would hand the renderer a buffer built
// from whatever happened to follow the header in memory.
SOL_TEST(theMeshLoaderRefusesABadMagicABadVersionAndATruncatedFile)
{
    assets::MeshData mesh;
    mesh.vertices = {{{0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},
                     {{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},
                     {{0.0f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f}}};
    mesh.indices = {0, 1, 2};
    const std::vector<std::uint8_t> good = cooker::encodeMesh(mesh);
    const std::string path = std::string(platform::executableDirectory()) + "test_bad.smesh";

    assets::MeshData loaded;
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), good.data(), good.size()));
    SOL_CHECK(assets::loadMesh(path.c_str(), loaded)); // the positive control

    std::vector<std::uint8_t> wrongMagic = good;
    wrongMagic[0] ^= 0xFFu;
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), wrongMagic.data(), wrongMagic.size()));
    SOL_CHECK(!assets::loadMesh(path.c_str(), loaded));

    std::vector<std::uint8_t> wrongVersion = good;
    const std::uint32_t bumped = assets::kFormatVersion + 1;
    std::memcpy(wrongVersion.data() + sizeof(std::uint32_t), &bumped, sizeof(bumped));
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), wrongVersion.data(), wrongVersion.size()));
    SOL_CHECK(!assets::loadMesh(path.c_str(), loaded));

    // A count that promises more than the file holds is a size mismatch, not a
    // short read - the same rule the sound loader keeps two tests above.
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), good.data(), good.size() - 4));
    SOL_CHECK(!assets::loadMesh(path.c_str(), loaded));

    std::remove(path.c_str());
}

// A source that does not parse, and one that parses into nothing, both fail the
// import rather than cooking an empty mesh the game would draw as a hole.
SOL_TEST(theForgeImportRefusesASourceThatBuildsNoGeometry)
{
    const std::string path = std::string(platform::executableDirectory()) + "test_empty.forge";
    const std::string empty = "name = \"nothing\"\n";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), empty.data(), empty.size()));

    assets::MeshData mesh;
    std::string error;
    SOL_CHECK(!cooker::importForgeMesh(path.c_str(), mesh, &error));
    SOL_CHECK(!error.empty());

    const std::string broken = "name = \"bad\"\n[[part]]\nid = \"x\"\ntype = \"not_a_shape\"\n";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), broken.data(), broken.size()));
    error.clear();
    SOL_CHECK(!cooker::importForgeMesh(path.c_str(), mesh, &error));
    SOL_CHECK(!error.empty());

    error.clear();
    SOL_CHECK(!cooker::importForgeMesh("no_such_file.forge", mesh, &error));
    SOL_CHECK(!error.empty());

    std::remove(path.c_str());
}

// ---------------------------------------------------------------------------
// The level set (engine plan Phase 9 stage F). A `.forge` no longer cooks to
// one file, and the two things that can go wrong with a set of files are the
// naming and the leftovers.
// ---------------------------------------------------------------------------

SOL_TEST(aLevelIsNamedBesideTheMeshItBelongsTo)
{
    const std::string base = "cooked/station.smesh";
    SOL_CHECK(cooker::meshLevelPath(base, 0) == base);
    SOL_CHECK(cooker::meshLevelPath(base, 1) == "cooked/station.lod1.smesh");
    SOL_CHECK(cooker::meshLevelPath(base, 2) == "cooked/station.lod2.smesh");
    // A path with no extension still names something usable rather than
    // splicing ".lod1" into the middle of a directory name.
    SOL_CHECK(cooker::meshLevelPath("cooked/station", 1) == "cooked/station.lod1");
}

namespace {

// A triangle at a stated size, so the levels below are distinguishable by
// their contents rather than only by their names.
[[nodiscard]] assets::MeshData oneTriangle(float scale)
{
    assets::MeshData mesh;
    mesh.vertices = {{{0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},
                     {{scale, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},
                     {{0.0f, 0.0f, scale}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f}}};
    mesh.indices = {0, 1, 2};
    return mesh;
}

[[nodiscard]] assets::LodChain chainOf(std::initializer_list<float> scales)
{
    assets::LodChain chain;
    for (const float scale : scales) {
        assets::MeshLevel level;
        level.mesh = oneTriangle(scale);
        level.triangles = 1;
        chain.levels.push_back(std::move(level));
    }
    return chain;
}

} // namespace

// ⚑⚑ THE TRAP THIS STAGE ADDS, AND IT IS THE ONE THAT WOULD NEVER BE NOTICED:
// a cooked directory is not rebuilt from scratch, so an asset edited below the
// triangle floor - or one whose second level stops clearing a band - leaves a
// `.lod2.smesh` behind that the runtime would load and draw AT DISTANCE, which
// is precisely where nobody is looking closely enough to catch it.
SOL_TEST(cookingAShorterChainDeletesTheLevelsItNoLongerProduces)
{
    const std::string base = std::string(platform::executableDirectory()) + "test_levels.smesh";
    std::string error;
    std::uint32_t written = 0;

    SOL_REQUIRE(cooker::writeMeshLevels(oneTriangle(1.0f), chainOf({0.5f, 0.25f}), base, written, &error));
    SOL_CHECK(error.empty());
    SOL_CHECK(written == 3); // level 0 and two below it
    for (std::uint32_t level = 0; level < 3; ++level) {
        assets::MeshData loaded;
        SOL_CHECK(assets::loadMesh(cooker::meshLevelPath(base, level).c_str(), loaded));
    }

    // Now the same asset cooks to fewer levels. The positive control is in the
    // same run: level 0 must still be there afterwards, so this is a deletion
    // and not a wipe.
    SOL_REQUIRE(cooker::writeMeshLevels(oneTriangle(1.0f), chainOf({0.5f}), base, written, &error));
    SOL_CHECK(written == 2);
    assets::MeshData loaded;
    SOL_CHECK(assets::loadMesh(cooker::meshLevelPath(base, 0).c_str(), loaded));
    SOL_CHECK(assets::loadMesh(cooker::meshLevelPath(base, 1).c_str(), loaded));
    SOL_CHECK(!assets::loadMesh(cooker::meshLevelPath(base, 2).c_str(), loaded));

    // And a chain of none leaves exactly one file behind.
    SOL_REQUIRE(cooker::writeMeshLevels(oneTriangle(1.0f), {}, base, written, &error));
    SOL_CHECK(written == 1);
    SOL_CHECK(assets::loadMesh(cooker::meshLevelPath(base, 0).c_str(), loaded));
    SOL_CHECK(!assets::loadMesh(cooker::meshLevelPath(base, 1).c_str(), loaded));

    for (std::uint32_t level = 0; level < 3; ++level) {
        std::remove(cooker::meshLevelPath(base, level).c_str());
    }
}

// ⚑ Level 0 is the bytes the game already loads, and stage F must not have
// moved them. `writeMeshLevels` has to write exactly what `encodeMesh` alone
// would have written - the claim `cooker.unit`'s end-to-end test and E3's
// bake-save-recook recipe both rest on.
SOL_TEST(theLevelZeroFileIsExactlyWhatTheEncoderAloneWouldHaveWritten)
{
    const std::string base = std::string(platform::executableDirectory()) + "test_level0.smesh";
    const assets::MeshData source = oneTriangle(3.0f);
    std::string error;
    std::uint32_t written = 0;
    SOL_REQUIRE(cooker::writeMeshLevels(source, chainOf({0.5f}), base, written, &error));

    std::vector<std::uint8_t> onDisk;
    SOL_REQUIRE(platform::readFileBytes(base.c_str(), onDisk));
    const std::vector<std::uint8_t> expected = cooker::encodeMesh(source);
    SOL_REQUIRE(onDisk.size() == expected.size());
    SOL_CHECK(std::memcmp(onDisk.data(), expected.data(), expected.size()) == 0);

    for (std::uint32_t level = 0; level < 2; ++level) {
        std::remove(cooker::meshLevelPath(base, level).c_str());
    }
}

// The committed assets, through the cook the cooker actually runs: whatever
// chain the policy produces must reach the game through the runtime's own
// loader, and every level must be a mesh rather than a file that merely exists.
SOL_TEST(everyLevelACommittedForgeProducesLoadsThroughTheRuntimeLoader)
{
    const char* const names[] = {"cube", "gate", "ship", "station", "cockpit", "asteroid"};
    std::uint32_t chainsSeen = 0;
    for (const char* name : names) {
        const std::string sourcePath = std::string(SOL_MESH_SOURCE_DIR) + "/" + name + ".forge";
        assets::MeshData built;
        std::string error;
        SOL_REQUIRE(cooker::importForgeMesh(sourcePath.c_str(), built, &error));

        const assets::LodChain chain = assets::buildLodChain(built);
        const std::string base =
            std::string(platform::executableDirectory()) + "test_chain_" + name + ".smesh";
        std::uint32_t written = 0;
        SOL_REQUIRE(cooker::writeMeshLevels(built, chain, base, written, &error));
        SOL_CHECK(written == chain.levels.size() + 1);

        for (std::uint32_t level = 1; level <= chain.levels.size(); ++level) {
            assets::MeshData loaded;
            SOL_REQUIRE(assets::loadMesh(cooker::meshLevelPath(base, level).c_str(), loaded));
            SOL_CHECK(!loaded.vertices.empty());
            SOL_CHECK(loaded.indices.size() % 3 == 0);
            SOL_CHECK(loaded.indices.size() == chain.levels[level - 1].mesh.indices.size());
            ++chainsSeen;
        }
        for (std::uint32_t level = 0; level <= chain.levels.size(); ++level) {
            std::remove(cooker::meshLevelPath(base, level).c_str());
        }
    }
    SOL_CHECK(chainsSeen > 0); // never a vacuous pass
}

// ⚑ The layout the game loads, asserted end to end for the first time. The mip
// chain and the header used to be assembled in the cooker's `main.cpp`, outside
// the library this suite links - the same shape that kept `.smesh` untestable
// until the E1-E3 debt slice moved `encodeMesh`. Stage G moved this one because
// the Forge needed to call it too, and a second mip loop in the tool would be a
// second answer to what a cooked texture is.
SOL_TEST(textureRoundTripsThroughTheCookedFormat)
{
    cooker::ImageRgba image;
    image.width = 8;
    image.height = 8;
    image.pixels.assign(static_cast<std::size_t>(image.width) * image.height * 4, 0);
    for (std::size_t i = 0; i < image.pixels.size(); i += 4) {
        image.pixels[i] = 200;    // r
        image.pixels[i + 1] = 40; // g
        image.pixels[i + 2] = 90; // b
        image.pixels[i + 3] = 255;
    }

    const assets::TextureData encoded = cooker::encodeTexture(image);
    SOL_CHECK(encoded.width == 8);
    SOL_CHECK(encoded.height == 8);
    SOL_CHECK(encoded.format == assets::TextureFormat::BC1);
    // 8, 4, 2, 1 - the chain runs to a single texel rather than stopping at a
    // block, because a mip smaller than 4x4 is still a mip the sampler wants.
    SOL_REQUIRE(encoded.mips.size() == 4);
    SOL_CHECK(encoded.mips[0].size() == 8 * 8 / 16 * 8);

    const std::vector<std::uint8_t> bytes = cooker::serializeTexture(encoded);
    std::size_t payload = 0;
    for (const std::vector<std::uint8_t>& mip : encoded.mips) {
        payload += mip.size();
    }
    SOL_CHECK(bytes.size() == sizeof(assets::TextureFileHeader) + payload);

    const std::string path = std::string(platform::executableDirectory()) + "test_roundtrip.stex";
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), bytes.data(), bytes.size()));

    assets::TextureData loaded;
    SOL_REQUIRE(assets::loadTexture(path.c_str(), loaded));
    SOL_CHECK(loaded.width == encoded.width);
    SOL_CHECK(loaded.height == encoded.height);
    SOL_CHECK(loaded.format == encoded.format);
    SOL_REQUIRE(loaded.mips.size() == encoded.mips.size());
    for (std::size_t i = 0; i < loaded.mips.size(); ++i) {
        SOL_CHECK(loaded.mips[i] == encoded.mips[i]);
    }

    // A truncated payload is a size mismatch, not a short read.
    SOL_REQUIRE(platform::writeFileBytes(path.c_str(), bytes.data(), bytes.size() - 2));
    assets::TextureData shortLoad;
    SOL_CHECK(!assets::loadTexture(path.c_str(), shortLoad));

    std::remove(path.c_str());
}

// --- the cook itself (Phase 24 stage T) ---
//
// ⚑⚑ EVERY TEST BELOW IS ABOUT CODE THAT HAS BEEN UNTESTED SINCE PHASE 5, and
// none of it was hard to test - it sat in `tools/cooker/src/main.cpp`, which
// this suite does not link. The dispatch decides what every asset in the game
// becomes, the collision guard can stop an entire build, and the stray sweep
// DELETES. Stage T moved them into `cook.hpp` and this is what that bought.

namespace {

// One scratch root beneath the test binary, with a source and an output tree
// under it, reused by every cook test.
//
// ⚑ `platform` deletes files and not directories, so the three empty
// directories a run leaves behind are deliberate residue of the same kind
// `platform.unit` already leaves - and the name is this suite's, never a real
// cooked directory's, so a test run cannot collide with a real cook.
std::string cookScratchRoot()
{
    return std::string(platform::executableDirectory()) + "cook_scratch/";
}

std::string cookSourceDirectory()
{
    return cookScratchRoot() + "src";
}

std::string cookOutputDirectory()
{
    return cookScratchRoot() + "out";
}

// ⚑ Returns a bool rather than asserting: SOL_REQUIRE returns from the function
// it is written in, so a helper that used it would fail by carrying on.
[[nodiscard]] bool resetCookScratch()
{
    if (!platform::createDirectories(cookSourceDirectory().c_str()) ||
        !platform::createDirectories(cookOutputDirectory().c_str())) {
        return false;
    }
    for (const std::string& directory : {cookSourceDirectory(), cookOutputDirectory()}) {
        for (const std::string& path : platform::listFiles(directory.c_str())) {
            if (!platform::deleteFile(path.c_str())) {
                return false;
            }
        }
    }
    return true;
}

[[nodiscard]] bool writeScratchFile(const std::string& path, const std::vector<std::uint8_t>& bytes)
{
    return platform::writeFileBytes(path.c_str(), bytes.data(), bytes.size());
}

[[nodiscard]] bool fileExists(const std::string& path)
{
    return platform::fileModificationTime(path.c_str()) != 0;
}

// The cheapest real source this suite can cook: four silent frames of mono.
std::vector<std::uint8_t> tinyWav()
{
    return buildWav(1, 1, 22050, 16, pcm16Payload({0, 0, 0, 0}));
}

} // namespace

SOL_TEST(theDispatchIsByExtensionAndTheOutputIsKeyedOnTheStem)
{
    SOL_CHECK(cooker::cookKindForSource("a/b/hull.png") == cooker::CookKind::Texture);
    SOL_CHECK(cooker::cookKindForSource("a/b/hull.tex") == cooker::CookKind::TextureDoc);
    SOL_CHECK(cooker::cookKindForSource("a/b/hull.gltf") == cooker::CookKind::Mesh);
    SOL_CHECK(cooker::cookKindForSource("a/b/hull.glb") == cooker::CookKind::Mesh);
    SOL_CHECK(cooker::cookKindForSource("a/b/hull.forge") == cooker::CookKind::ForgeMesh);
    SOL_CHECK(cooker::cookKindForSource("a/b/ui.font") == cooker::CookKind::Font);
    SOL_CHECK(cooker::cookKindForSource("a/b/thrust.wav") == cooker::CookKind::Sound);
    SOL_CHECK(cooker::cookKindForSource("a/b/thrust.ogg") == cooker::CookKind::Sound);

    // Blender hands back `.GLTF` on a case-preserving filesystem and means the
    // same file kind.
    SOL_CHECK(cooker::cookKindForSource("a/b/HULL.GLTF") == cooker::CookKind::Mesh);

    // ⚑ What a source tree holds that is not a source, and the `.ttf` is the one
    // that matters: a `.font` manifest names the TTFs beside it, so a cooker
    // that treated one as a source would be inventing an asset nobody asked
    // for. Skipping is silent because it is the ordinary case.
    SOL_CHECK(cooker::cookKindForSource("a/b/.gitkeep") == cooker::CookKind::None);
    SOL_CHECK(cooker::cookKindForSource("a/b/Inter.ttf") == cooker::CookKind::None);
    SOL_CHECK(cooker::cookKindForSource("a/b/README.md") == cooker::CookKind::None);
    SOL_CHECK(cooker::cookKindForSource("a/b/noextension") == cooker::CookKind::None);
    SOL_CHECK(cooker::cookedExtension(cooker::CookKind::None)[0] == '\0');

    // ⚑ The source tree is deep and the output is FLAT: a cooked name is what a
    // `[[model]]` row names, and rows carry no paths.
    const std::vector<cooker::CookJob> jobs = cooker::planCook(
        {"assets/meshes/hull.forge", "assets/fonts/Inter.ttf", "assets/sounds/deep/thrust.wav"},
        "out/cooked");
    SOL_REQUIRE(jobs.size() == 2);
    SOL_CHECK(jobs[0].kind == cooker::CookKind::ForgeMesh);
    SOL_CHECK(jobs[0].output == "out/cooked/hull.smesh");
    SOL_CHECK(jobs[1].kind == cooker::CookKind::Sound);
    SOL_CHECK(jobs[1].output == "out/cooked/thrust.saud");
}

SOL_TEST(anOutputDirectoryIsSpelledOneWayHoweverTheCallerSpelledIt)
{
    // ⚑ FOUND BY RUNNING THE FORGE ON LINUX. The tool hands over
    // `executableDirectory() + "cooked/"` - built for concatenation, so it ends
    // in a separator - and the cook logged `bin/cooked//ship.smesh`. The
    // filesystem does not care and neither does the sweep, which compares
    // LISTED paths rather than job paths; but a job path that does not equal
    // the path the same file lists back as is the shape of every path bug this
    // repo has had, so it is normalised once rather than trusted.
    const std::vector<cooker::CookJob> trailing = cooker::planCook({"a/hull.tex"}, "out/cooked/");
    SOL_REQUIRE(trailing.size() == 1);
    SOL_CHECK(trailing[0].output == "out/cooked/hull.stex");

    // Several, and the caller's own separator convention: `platform::listFiles`
    // promises '/', which is what makes that the right spelling here too.
    const std::vector<cooker::CookJob> windows =
        cooker::planCook({"a/hull.tex"}, ".\\build\\bin\\cooked\\\\");
    SOL_REQUIRE(windows.size() == 1);
    SOL_CHECK(windows[0].output == "./build/bin/cooked/hull.stex");

    // ⚑ The stripping stops at one character, so a lone separator stays a
    // directory: "" here would silently turn an absolute output path into a
    // relative one, which is the only way this normalisation could do harm.
    SOL_CHECK(cooker::planCook({"a/hull.tex"}, "/")[0].output == "//hull.stex");
}

SOL_TEST(twoSourcesThatCookToOneOutputAreACollisionHoweverFarApartTheySit)
{
    // The pair that made this reachable at all: `.forge` and `.gltf` are
    // different extensions in different directories, and the output is keyed on
    // the stem. It was unreachable while `.gltf` was the only mesh source.
    const std::vector<cooker::CookJob> jobs = cooker::planCook(
        {"assets/meshes/gate.forge", "blender-inbox/gate.gltf", "assets/textures/hull.tex"}, "out");
    SOL_REQUIRE(jobs.size() == 3);

    const std::vector<cooker::CookCollision> collisions = cooker::cookCollisions(jobs);
    SOL_REQUIRE(collisions.size() == 1);
    SOL_CHECK(collisions[0].firstSource == "assets/meshes/gate.forge");
    SOL_CHECK(collisions[0].secondSource == "blender-inbox/gate.gltf");
    SOL_CHECK(collisions[0].output == "out/gate.smesh");

    // ⚑ The same stem with different cooked extensions is NOT a collision -
    // `hull.tex` and `hull.forge` are a texture and a mesh, which is the normal
    // way an author names a thing and its skin.
    SOL_CHECK(cooker::cookCollisions(cooker::planCook({"a/hull.tex", "b/hull.forge"}, "out")).empty());

    // ⚑⚑ AND THE PAIR PHASE 24 STAGE U2 MADE ORDINARY: two TEXTURE sources
    // sharing a stem. `hull.png` beside `hull.tex` is what an author produces by
    // painting a texture and naming it after the thing it goes on, and until the
    // Forge could list a `.png` nobody would have put one there.
    const std::vector<cooker::CookCollision> textures = cooker::cookCollisions(
        cooker::planCook({"assets/textures/hull.tex", "assets/textures/hull.png"}, "out"));
    SOL_REQUIRE(textures.size() == 1);
    SOL_CHECK(textures[0].output == "out/hull.stex");
}

// ⚑⚑⚑ THE REFUSAL NAMES THE TWO FILES, BECAUSE A COUNT IS NOT AN ANSWER TO THIS
// QUESTION (Phase 24 stage U2). It read "2 output collision(s); nothing cooked"
// with the filenames going only to the log - which is fine for `cooker.exe`,
// whose entire output IS the log, and useless in the Forge's status bar, the
// only surface an author inside the tool has. The whole content of this failure
// is WHICH TWO FILES, so the sentence carries them.
SOL_TEST(aCollisionRefusalNamesTheFilesRatherThanCountingThem)
{
    SOL_CHECK(cooker::collisionSentence({}).empty());

    const std::vector<cooker::CookCollision> one = cooker::cookCollisions(
        cooker::planCook({"assets/textures/hull.tex", "assets/textures/hull.png"}, "out"));
    // ⚑ Base names, not paths: the sentence has to fit one line and is read by
    // somebody who already knows where their own project is. The per-collision
    // LOG lines keep the full paths, which is where you go to find out exactly
    // which two files on disk are fighting.
    SOL_CHECK(cooker::collisionSentence(one) ==
              "hull.tex and hull.png both cook to hull.stex; nothing cooked");

    const std::vector<cooker::CookCollision> several = cooker::cookCollisions(cooker::planCook(
        {"a/hull.tex", "b/hull.png", "a/gate.forge", "b/gate.gltf", "a/beep.wav", "b/beep.ogg"}, "out"));
    SOL_REQUIRE(several.size() == 3);
    // The first pair in full, the rest counted: naming all of them would push
    // the one an author can act on off the end of the bar.
    SOL_CHECK(cooker::collisionSentence(several) ==
              "hull.tex and hull.png both cook to hull.stex (+2 more); nothing cooked");
}

SOL_TEST(aPartTreeAlwaysCooksAndAFontManifestWatchesTheFilesBesideIt)
{
    // ⚑ A `.forge` cooks to a level SET whose size is not knowable without
    // building the mesh, so a timestamp check would let a stale `.lod2.smesh`
    // survive a re-cook and be drawn at distance, where nobody is looking.
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::ForgeMesh) == cooker::StalenessRule::AlwaysCook);
    // A manifest's own timestamp does not move when a TTF it names is edited.
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::Font) ==
              cooker::StalenessRule::TimestampAndSiblings);
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::Texture) == cooker::StalenessRule::Timestamp);
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::TextureDoc) == cooker::StalenessRule::Timestamp);
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::Mesh) == cooker::StalenessRule::Timestamp);
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::Sound) == cooker::StalenessRule::Timestamp);
}

SOL_TEST(aRefusalAndAFailureAreDifferentSentencesBecauseTheyAreDifferentNews)
{
    cooker::CookReport ran;
    ran.cooked = 3;
    ran.skipped = 5;
    SOL_CHECK(ran.ok());
    SOL_CHECK(ran.summary() == "3 cooked, 5 up to date, 0 failed");

    cooker::CookReport partial = ran;
    partial.failed = 1;
    SOL_CHECK(!partial.ok());
    SOL_CHECK(partial.summary() == "3 cooked, 5 up to date, 1 failed");

    // ⚑ A refusal is not a failure count. Nothing was attempted, so the output
    // directory is exactly as it was - and "0 failed" would be true and
    // useless. This is the line the Forge's status bar shows.
    cooker::CookReport refused;
    refused.refusal = "hull.tex and hull.png both cook to hull.stex; nothing cooked";
    SOL_CHECK(!refused.ok());
    SOL_CHECK(refused.summary() == "hull.tex and hull.png both cook to hull.stex; nothing cooked");
}

SOL_TEST(cookingTheSameDirectoryTwiceCooksOnceAndThenSkips)
{
    SOL_REQUIRE(resetCookScratch());
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/beep.wav", tinyWav()));

    const cooker::CookReport first = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(first.ok());
    SOL_CHECK(first.cooked == 1 && first.skipped == 0 && first.failed == 0);
    SOL_CHECK(fileExists(cookOutputDirectory() + "/beep.saud"));

    const cooker::CookReport second = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(second.ok());
    SOL_CHECK(second.cooked == 0 && second.skipped == 1 && second.failed == 0);
}

SOL_TEST(anOutputCollisionRefusesTheWholeCookAndWritesNothing)
{
    SOL_REQUIRE(resetCookScratch());
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/beep.wav", tinyWav()));
    // Junk, and it is never read: the collision is found from the PLAN, before
    // a single source is opened.
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/beep.ogg", std::vector<std::uint8_t>(64, 7)));

    const cooker::CookReport report = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(!report.ok());
    // ⚑ `.ogg` before `.wav` because the pair is named in LISTING order, which is
    // sorted - not in the order an author happens to think of the two files.
    SOL_CHECK(report.refusal == "beep.ogg and beep.wav both cook to beep.saud; nothing cooked");
    SOL_CHECK(report.cooked == 0 && report.failed == 0);
    // ⚑ The VALID half of the pair did not cook either, and that is the whole
    // rule: whichever cooked last would silently win, and the staleness check
    // would then report the loser as up to date.
    SOL_CHECK(!fileExists(cookOutputDirectory() + "/beep.saud"));
}

SOL_TEST(anOutputWhoseSourceIsDeletedIsSweptOnTheNextCook)
{
    SOL_REQUIRE(resetCookScratch());
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/beep.wav", tinyWav()));
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/boop.wav", tinyWav()));
    SOL_REQUIRE(cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory()).cooked == 2);

    SOL_REQUIRE(platform::deleteFile((cookSourceDirectory() + "/boop.wav").c_str()));

    const cooker::CookReport report = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(report.ok());
    SOL_CHECK(!fileExists(cookOutputDirectory() + "/boop.saud"));
    // The positive control, in the same run: this is a deletion and not a wipe.
    SOL_CHECK(fileExists(cookOutputDirectory() + "/beep.saud"));
}

SOL_TEST(theSweepIsSkippedAfterAFailureSoABuildErrorIsNotAlsoAMissingAsset)
{
    SOL_REQUIRE(resetCookScratch());
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/beep.wav", tinyWav()));
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/boop.wav", tinyWav()));
    SOL_REQUIRE(cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory()).cooked == 2);

    // One source goes away and, in the same edit, another stops cooking - which
    // is what a real broken edit looks like.
    SOL_REQUIRE(platform::deleteFile((cookSourceDirectory() + "/boop.wav").c_str()));
    SOL_REQUIRE(writeScratchFile(cookSourceDirectory() + "/broken.png", std::vector<std::uint8_t>(64, 7)));

    const cooker::CookReport report = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(!report.ok());
    SOL_CHECK(report.failed == 1);
    // ⚑ The stray survives the failing run. A job that failed may not have
    // written its output, so deleting a previous good one here would turn a
    // build error into a missing asset - two problems where there was one.
    SOL_CHECK(fileExists(cookOutputDirectory() + "/boop.saud"));
}

SOL_TEST(withNoSourcesTheCookLeavesTheOutputDirectoryAloneRatherThanEmptyingIt)
{
    SOL_REQUIRE(resetCookScratch());
    // ⚑ An empty source tree is exactly what a MISTYPED source path looks like
    // from inside the cook: `listFiles` on a directory that does not exist
    // returns nothing and reports nothing wrong. Without the guard, every
    // cooked file is unclaimed and the sweep empties the directory.
    SOL_REQUIRE(writeScratchFile(cookOutputDirectory() + "/hull.stex", std::vector<std::uint8_t>(64, 7)));

    const cooker::CookReport report = cooker::cookDirectory(cookSourceDirectory(), cookOutputDirectory());
    SOL_CHECK(report.ok());
    SOL_CHECK(report.cooked == 0 && report.skipped == 0 && report.failed == 0);
    SOL_CHECK(fileExists(cookOutputDirectory() + "/hull.stex"));

    // The last test in the group, so it takes the file with it: what a run
    // leaves behind is then two empty directories and nothing that looks like a
    // cooked asset sitting beside a real one.
    SOL_CHECK(platform::deleteFile((cookOutputDirectory() + "/hull.stex").c_str()));
}

// --- stage U3: the base-colour image of a node's material --------------------

namespace {

void appendBytes(std::vector<std::uint8_t>& out, const void* data, std::size_t size)
{
    const std::uint8_t* bytes = static_cast<const std::uint8_t*>(data);
    out.insert(out.end(), bytes, bytes + size);
}

void padToFour(std::vector<std::uint8_t>& out, std::uint8_t filler)
{
    while (out.size() % 4 != 0) {
        out.push_back(filler);
    }
}

// ⚑⚑ A REAL GLB, BECAUSE A GLB IS WHAT THE BRIDGE PRODUCES AND THIS SUITE HAD
// NEVER BUILT ONE. `sol_forge_bridge.py` exports `export_format: "GLB"`, and a
// GLB is the container that packs an image into a BUFFER VIEW - so a test that
// reached the image through a data uri instead would exercise a path no
// author's file ever takes, and would leave the common one uncovered. The
// header is 12 bytes, then length-prefixed chunks, each padded to four.
std::vector<std::uint8_t> buildGlb(const std::string& json, const std::vector<std::uint8_t>& bin)
{
    std::vector<std::uint8_t> jsonChunk(json.begin(), json.end());
    padToFour(jsonChunk, ' '); // spaces, per the spec: the JSON must stay parseable
    std::vector<std::uint8_t> binChunk = bin;
    padToFour(binChunk, 0);

    std::vector<std::uint8_t> glb;
    const std::uint32_t version = 2;
    const std::uint32_t total = 12 + 8 + static_cast<std::uint32_t>(jsonChunk.size()) + 8 +
                                static_cast<std::uint32_t>(binChunk.size());
    appendBytes(glb, "glTF", 4);
    appendBytes(glb, &version, 4);
    appendBytes(glb, &total, 4);

    const std::uint32_t jsonLength = static_cast<std::uint32_t>(jsonChunk.size());
    const std::uint32_t jsonType = 0x4E4F534Au; // "JSON"
    appendBytes(glb, &jsonLength, 4);
    appendBytes(glb, &jsonType, 4);
    appendBytes(glb, jsonChunk.data(), jsonChunk.size());

    const std::uint32_t binLength = static_cast<std::uint32_t>(binChunk.size());
    const std::uint32_t binType = 0x004E4942u; // "BIN\0"
    appendBytes(glb, &binLength, 4);
    appendBytes(glb, &binType, 4);
    appendBytes(glb, binChunk.data(), binChunk.size());
    return glb;
}

// One triangle, then a whole image file, laid out the way an exporter lays them
// out: geometry first, each view starting on a four-byte boundary.
std::vector<std::uint8_t>
triangleAndImageBin(const std::uint8_t* image, std::size_t imageLength, std::size_t& imageOffset)
{
    const float positions[9] = {0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f};
    const std::uint16_t indices[3] = {0, 1, 2};
    std::vector<std::uint8_t> bin;
    appendBytes(bin, positions, sizeof(positions));
    appendBytes(bin, indices, sizeof(indices));
    padToFour(bin, 0);
    imageOffset = bin.size();
    appendBytes(bin, image, imageLength);
    return bin;
}

// The JSON half, with the image's view spelled out by the caller so a test can
// move it. `primitives` and `materials` are handed in whole: what varies between
// these tests is how many surfaces the object has, not the rest of the file.
std::string texturedGltfJson(const std::string& primitives,
                             const std::string& materials,
                             std::size_t imageOffset,
                             std::size_t imageLength,
                             std::size_t bufferLength)
{
    return std::string(R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "Hull"}],
        "meshes": [{"primitives": [)") +
           primitives + R"(]}],
        "materials": [)" +
           materials +
           R"(],
        "textures": [{"source": 0}],
        "images": [{"name": "hull paint", "mimeType": "image/png", "bufferView": 2}],
        "buffers": [{"byteLength": )" +
           std::to_string(bufferLength) + R"(}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6},
            {"buffer": 0, "byteOffset": )" +
           std::to_string(imageOffset) + R"(, "byteLength": )" + std::to_string(imageLength) +
           R"(}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";
}

constexpr const char* kOneTexturedPrimitive =
    R"({"attributes": {"POSITION": 0}, "indices": 1, "material": 0})";
constexpr const char* kOneTexturedMaterial =
    R"({"name": "HullPaint", "pbrMetallicRoughness": {"baseColorTexture": {"index": 0}}})";

// Writes a GLB carrying `image` as its base-colour and imports it.
[[nodiscard]] bool importGlbWithImage(const char* name,
                                      const std::string& primitives,
                                      const std::string& materials,
                                      const std::uint8_t* image,
                                      std::size_t imageLength,
                                      std::vector<cooker::GltfPart>& parts)
{
    std::size_t imageOffset = 0;
    const std::vector<std::uint8_t> bin = triangleAndImageBin(image, imageLength, imageOffset);
    const std::string json = texturedGltfJson(primitives, materials, imageOffset, imageLength, bin.size());
    const std::vector<std::uint8_t> glb = buildGlb(json, bin);

    const std::string path = std::string(platform::executableDirectory()) + name;
    if (!platform::writeFileBytes(path.c_str(), glb.data(), glb.size())) {
        return false;
    }
    const bool ok = cooker::importGltfParts(path.c_str(), parts);
    std::remove(path.c_str());
    return ok;
}

} // namespace

// ⚑⚑⚑ THE STAGE'S CENTRAL CLAIM AS ONE ASSERTION: THE BYTES THAT COME OUT ARE
// THE BYTES THAT WENT IN. Not an image equal to them - the same file. That is
// what makes the write on the far side a copy rather than a re-encode, and it is
// the whole reason this stage needs no PNG ENCODER, which this repo does not
// have and which writing one to serve an import would have been.
SOL_TEST(aGlbsBaseColourImageArrivesAsTheExactBytesTheExporterEmbedded)
{
    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(importGlbWithImage("test_u3_textured.glb",
                                 kOneTexturedPrimitive,
                                 kOneTexturedMaterial,
                                 kPng2x2,
                                 sizeof(kPng2x2),
                                 parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_CHECK(parts[0].name == "Hull");
    SOL_CHECK(parts[0].imageNote.empty());
    SOL_REQUIRE(parts[0].imageBytes.size() == sizeof(kPng2x2));
    SOL_CHECK(std::memcmp(parts[0].imageBytes.data(), kPng2x2, sizeof(kPng2x2)) == 0);
    // The image's own name, not the material's: it is what the author sees in
    // Blender's image editor, and the material is only the fallback.
    SOL_CHECK(parts[0].imageName == "hull paint");
    // And the geometry still came through, which is the thing an image must
    // never be able to cost.
    SOL_CHECK(parts[0].mesh.vertices.size() == 3 && parts[0].mesh.indices.size() == 3);
}

// ⚑⚑ THE ONE-TEXTURE-PER-MESH RULE, AND BOTH SHAPES OF BREAKING IT. The engine
// draws one texture per mesh, so an object with two surfaces has no answer -
// and the failure this refuses is not an error, it is SILENCE: taking whichever
// material happened to be first would give the author a textured mesh that is
// wrong in a way nothing on screen distinguishes from right.
SOL_TEST(anObjectWithTwoMaterialsIsReportedRatherThanFlattenedIntoWhicheverWon)
{
    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(importGlbWithImage("test_u3_two_materials.glb",
                                 std::string(kOneTexturedPrimitive) +
                                     R"(, {"attributes": {"POSITION": 0}, "indices": 1, "material": 1})",
                                 std::string(kOneTexturedMaterial) + R"(, {"name": "Trim"})",
                                 kPng2x2,
                                 sizeof(kPng2x2),
                                 parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_CHECK(parts[0].imageBytes.empty());
    SOL_CHECK(parts[0].imageNote.find("2 materials") != std::string::npos);

    // ⚑⚑⚑ AND THE SHAPE THAT IS EASY TO GET WRONG: one primitive naming a
    // material and one naming NONE. glTF's default material is a real surface
    // rather than an absent one, so this is still a two-surface object - and an
    // implementation that counted only the primitives carrying a `material` key
    // would see ONE material here and take the texture silently, which is
    // exactly the flattening the case above refuses.
    std::vector<cooker::GltfPart> mixed;
    SOL_CHECK(importGlbWithImage("test_u3_default_material.glb",
                                 std::string(kOneTexturedPrimitive) +
                                     R"(, {"attributes": {"POSITION": 0}, "indices": 1})",
                                 kOneTexturedMaterial,
                                 kPng2x2,
                                 sizeof(kPng2x2),
                                 mixed));
    SOL_REQUIRE(mixed.size() == 1);
    SOL_CHECK(mixed[0].imageBytes.empty());
    SOL_CHECK(mixed[0].imageNote.find("2 materials") != std::string::npos);
}

// ⚑⚑ A FORMAT THIS PIPELINE CANNOT READ IS NAMED HERE, WHERE THE AUTHOR CAN ACT
// ON IT. Blender's exporter writes JPEG for a JPEG source and there is no "always
// PNG" to ask it for, so this is reachable by anybody who painted in one. Left
// alone it would be written under a `.png` name and fail much later inside
// `decodePng` - a message about a DECODER, for a file the author never chose the
// format of. The signature decides, not the `mimeType`, which is why this fixture
// claims `image/png` and is not one.
SOL_TEST(aBaseColourImageThisPipelineCannotReadIsRefusedByNameRatherThanBySilence)
{
    // A JPEG's first three bytes, then nothing that matters: what is under test
    // is the refusal, and reaching it does not require a decodable file.
    std::vector<std::uint8_t> jpeg(64, 0);
    jpeg[0] = 0xFF;
    jpeg[1] = 0xD8;
    jpeg[2] = 0xFF;

    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(importGlbWithImage(
        "test_u3_jpeg.glb", kOneTexturedPrimitive, kOneTexturedMaterial, jpeg.data(), jpeg.size(), parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_CHECK(parts[0].imageBytes.empty());
    SOL_CHECK(parts[0].imageNote.find("a JPEG") != std::string::npos);
    // Named as the material an author would go and open, not as an index.
    SOL_CHECK(parts[0].imageNote.find("HullPaint") != std::string::npos);
    // ⚑ The mesh is untouched. A texture that cannot be read must not cost the
    // geometry that imported perfectly beside it.
    SOL_CHECK(parts[0].mesh.vertices.size() == 3);
}

// The `.gltf` half of the same chain: an image behind a data uri rather than a
// buffer view. It is the fallback path rather than the bridge's, and it exists
// because a glTF from anywhere else may well take it.
SOL_TEST(anImageCarriedInADataUriResolvesTheSameAsOneInABufferView)
{
    const std::string encoded = cooker::encodeBase64(kPng2x2, sizeof(kPng2x2));
    const std::string json = std::string(R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "Hull"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1, "material": 0}]}],
        "materials": [{"name": "HullPaint", "pbrMetallicRoughness": {"baseColorTexture": {"index": 0}}}],
        "textures": [{"source": 0}],
        "images": [{"uri": "data:image/png;base64,)") +
                             encoded + R"("}],
        "buffers": [{"byteLength": 42, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_u3_datauri.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), json.data(), json.size()));

    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(cooker::importGltfParts(path.c_str(), parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_REQUIRE(parts[0].imageBytes.size() == sizeof(kPng2x2));
    SOL_CHECK(std::memcmp(parts[0].imageBytes.data(), kPng2x2, sizeof(kPng2x2)) == 0);
    // No image name in this file, so the material's is what is left.
    SOL_CHECK(parts[0].imageName == "HullPaint");

    std::remove(path.c_str());
}

// ⚑⚑⚑ THE ABSENCE, ASSERTED. Every mesh committed to this repo has no material
// and the bridge sent none for its whole life until this stage, so "no material"
// is the NORMAL case - and a note on it would fire on every existing asset and
// teach an author that the line means nothing. This is the negative control for
// the three tests above: they check that a problem is reported, and it checks
// that the absence of a problem is silent.
SOL_TEST(anObjectWithNoMaterialAtAllSaysNothingBecauseThatIsEveryMeshInThisRepo)
{
    const char* gltf = R"({
        "asset": {"version": "2.0"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "Plain"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0}, "indices": 1}]}],
        "buffers": [{"byteLength": 42, "uri":
            "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAAAAAAABAAIA"}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 36},
            {"buffer": 0, "byteOffset": 36, "byteLength": 6}
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 3, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5123, "count": 3, "type": "SCALAR"}
        ]
    })";

    const std::string path = std::string(platform::executableDirectory()) + "test_u3_plain.gltf";
    SOL_CHECK(platform::writeFileBytes(path.c_str(), gltf, std::strlen(gltf)));

    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(cooker::importGltfParts(path.c_str(), parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_CHECK(parts[0].imageBytes.empty());
    SOL_CHECK(parts[0].imageNote.empty());
    SOL_CHECK(parts[0].imageName.empty());

    std::remove(path.c_str());
}

// A material with a flat base colour and no image is silent for the same reason:
// it is a thing an author MEANT, and the model row's texture combo is where they
// say otherwise. This stage adds a route; it does not make one compulsory.
SOL_TEST(aMaterialWithNoBaseColourTextureIsAlsoSilent)
{
    std::vector<cooker::GltfPart> parts;
    SOL_CHECK(importGlbWithImage("test_u3_untextured_material.glb",
                                 kOneTexturedPrimitive,
                                 R"({"name": "FlatGrey", "pbrMetallicRoughness": {}})",
                                 kPng2x2,
                                 sizeof(kPng2x2),
                                 parts));
    SOL_REQUIRE(parts.size() == 1);
    SOL_CHECK(parts[0].imageBytes.empty());
    SOL_CHECK(parts[0].imageNote.empty());
}

// --- the transcription proof (Phase 26 stages A and B) -----------------------
//
// ⚑⚑⚑ THE PROOF OUTLIVED THE FILES IT WAS PROVED AGAINST, AND THAT IS A CHANGE
// OF KIND RATHER THAN OF DEGREE. Stage A compared two cues against the `.wav`
// they replace and matched sample for sample. Stage B deleted those wavs, and
// Phase 9 stage G's precedent would have ended the story there - "proved
// pixel-exact against the PNGs it replaced BEFORE THOSE WERE DELETED", a
// transcription-time proof that leaves nothing behind. The golden hashes below
// are the same proof frozen: they were computed from the WAV-DERIVED samples
// while both forms still existed, so a match here is still a statement about
// the PowerShell, not about this code agreeing with itself.
//
// ⚑⚑ AND FREEZING IT BUYS SOMETHING STAGE G NEVER GOT: THIS IS ALSO THE
// CROSS-PLATFORM DETERMINISM CHECK. The spec's finding 10 asked for a
// Windows/Linux diff of the cooked output, because a cue is ~57,000 samples of
// ACCUMULATING phase through `std::sin` and `std::exp` - a far longer chain
// than the few hundred independent evaluations `mesh_build.cpp` does. A hash
// that must match on both platforms runs that check on every build of both,
// instead of once by hand. ⚑ If this ever fails on one platform only, the
// finding is the libm difference and not this file.
//
// ⚑⚑ WHAT IT DOES NOT COVER, RESTATED SO NOBODY READS IT AS MORE: only
// `docking_chime` and `alarm` are analytic. The other seven carry noise, their
// samples CHANGED at stage B by design (Phase 26 decision 2), and nothing here
// pins them - `soundDocEveryCommittedCueBuilds` only asserts they are cues.

namespace {

// FNV-1a over the raw sample bytes. A hash rather than an inline array because
// 39,690 int16 values is not a fixture, and rather than a peak/RMS pair because
// those agree for waveforms that sound nothing alike.
[[nodiscard]] std::string sampleHash(const assets::SoundData& d)
{
    std::uint64_t h = 1469598103934665603ull;
    const auto* bytes = reinterpret_cast<const std::uint8_t*>(d.samples.data());
    const std::size_t n = d.samples.size() * sizeof(std::int16_t);
    for (std::size_t i = 0; i < n; ++i) {
        h ^= bytes[i];
        h *= 1099511628211ull;
    }
    char buffer[32];
    std::snprintf(buffer, sizeof(buffer), "%016llx", static_cast<unsigned long long>(h));
    return buffer;
}

[[nodiscard]] bool buildCommittedCue(const char* stem, assets::SoundData& out)
{
    const std::string path = std::string(SOL_SOUND_SOURCE_DIR) + "/" + stem + ".snd";
    std::vector<std::uint8_t> bytes;
    if (!platform::readFileBytes(path.c_str(), bytes)) {
        std::printf("  cannot read %s\n", path.c_str());
        return false;
    }
    assets::SoundDoc doc;
    std::string error;
    if (!assets::parseSound(
            reinterpret_cast<const char*>(bytes.data()), bytes.size(), path.c_str(), doc, &error)) {
        std::printf("  parse failed: %s\n", error.c_str());
        return false;
    }
    if (!assets::buildSound(doc, out, &error)) {
        std::printf("  build failed: %s\n", error.c_str());
        return false;
    }
    return true;
}

// Captured 2026-08-28 from the committed `.wav` files, at the commit that
// deleted them. Regenerating one of these to make a test pass is the one thing
// that would make this file worthless.
constexpr const char* kDockingChimeWavHash = "4fb9e8272c1b88ff";
constexpr const char* kAlarmWavHash = "725b35c2131536a8";

} // namespace

SOL_TEST(soundDocDockingChimeStillMatchesTheWavItReplaced)
{
    assets::SoundData snd;
    SOL_REQUIRE(buildCommittedCue("docking_chime", snd));
    SOL_CHECK(snd.sampleRate == 44100);
    SOL_CHECK(snd.channelCount == 1);
    SOL_CHECK(snd.frameCount() == 39690);
    SOL_CHECK(sampleHash(snd) == kDockingChimeWavHash);
}

SOL_TEST(soundDocAlarmStillMatchesTheWavItReplaced)
{
    assets::SoundData snd;
    SOL_REQUIRE(buildCommittedCue("alarm", snd));
    SOL_CHECK(snd.frameCount() == 39690);
    // ⚑ The cue that exercises `harmonic` and a six-segment sequence, so the
    // pair between them covers every analytic parameter the format has.
    SOL_CHECK(sampleHash(snd) == kAlarmWavHash);
}

SOL_TEST(soundDocProofWouldFailIfTheOpsWereWrong)
{
    // ⚑⚑ THE NEGATIVE CONTROL, because a hash comparison can pass while
    // measuring nothing if the thing hashed is not what the assertion claims.
    // One parameter moved by a hundredth must break the match.
    const std::string path = std::string(SOL_SOUND_SOURCE_DIR) + "/alarm.snd";
    std::vector<std::uint8_t> bytes;
    SOL_REQUIRE(platform::readFileBytes(path.c_str(), bytes));
    std::string text(reinterpret_cast<const char*>(bytes.data()), bytes.size());
    const std::size_t at = text.find("level = 0.75");
    SOL_REQUIRE(at != std::string::npos);
    text.replace(at, std::strlen("level = 0.75"), "level = 0.76");

    assets::SoundDoc doc;
    assets::SoundData off;
    std::string error;
    SOL_REQUIRE(assets::parseSound(text.c_str(), text.size(), "alarm.snd", doc, &error));
    SOL_REQUIRE(assets::buildSound(doc, off, &error));
    SOL_CHECK(off.frameCount() == 39690);
    SOL_CHECK(sampleHash(off) != kAlarmWavHash);
}

SOL_TEST(soundDocEveryCommittedCueBuilds)
{
    // ⚑⚑ THE NINE READ FROM `assets/sounds/` RATHER THAN FROM A FIXTURE, which
    // is the rule `geometry.unit` follows for `.forge` and `texture_doc_tests`
    // for `.tex`, and the reason Phase 9 stage D gave for it: a suite whose
    // ground truth is its own copy cannot tell you the shipped asset changed.
    const char* stems[] = {"weapon_fire",
                           "weapon_hit_shield",
                           "weapon_hit_hull",
                           "explosion",
                           "mining_cut",
                           "engine_loop",
                           "ui_click",
                           "docking_chime",
                           "alarm"};
    for (const char* stem : stems) {
        assets::SoundData cue;
        SOL_REQUIRE(buildCommittedCue(stem, cue));
        SOL_CHECK(cue.channelCount == 1);
        SOL_CHECK(cue.sampleRate == 44100);
        // A cue with no audible content is the one thing about a sound source
        // that is broken rather than merely unusual.
        SOL_CHECK(cue.frameCount() > 1000);
        std::int16_t loudest = 0;
        for (const std::int16_t sample : cue.samples) {
            loudest = std::max(loudest, static_cast<std::int16_t>(std::abs(static_cast<int>(sample))));
        }
        SOL_CHECK(loudest > 8000);
    }
}

SOL_TEST(soundDocEngineLoopJoinsItsOwnEndSoTheOneLoopingVoiceDoesNotTick)
{
    // ⚑⚑ ASSERTED ON THE SHIPPED ASSET, not on a synthetic one, because
    // `engine_loop` is the only cue in the game that loops and the only
    // consumer `loop_noise` has. If the crossfade regresses, the symptom is a
    // tick once every two seconds under thrust - audible, and nothing else in
    // the suite would catch it.
    assets::SoundData cue;
    SOL_REQUIRE(buildCommittedCue("engine_loop", cue));
    SOL_REQUIRE(cue.samples.size() > 1000);

    const int seam = std::abs(static_cast<int>(cue.samples.front()) - static_cast<int>(cue.samples.back()));
    int worst = 0;
    for (std::size_t i = 1; i < cue.samples.size(); ++i) {
        worst = std::max(worst,
                         std::abs(static_cast<int>(cue.samples[i]) - static_cast<int>(cue.samples[i - 1])));
    }
    SOL_CHECK(seam <= worst);
}

SOL_TEST(cookKindDispatchesSndToTheSoundDocument)
{
    SOL_CHECK(cooker::cookKindForSource("assets/sounds/alarm.snd") == cooker::CookKind::SoundDoc);
    SOL_CHECK(cooker::cookKindForSource("assets/sounds/alarm.wav") == cooker::CookKind::Sound);
    // ⚑ Both land on `.saud`: an authored cue and a recorded one are
    // indistinguishable by the time the game loads them, which is what keeps
    // the runtime out of this phase entirely - and why `.wav` staying
    // importable costs nothing (Phase 26 decision 5).
    SOL_CHECK(std::strcmp(cooker::cookedExtension(cooker::CookKind::SoundDoc), ".saud") == 0);
    SOL_CHECK(cooker::stalenessRuleFor(cooker::CookKind::SoundDoc) == cooker::StalenessRule::Timestamp);
}
