/// @file
/// Capability profiles derived from LunarG's desktop-baseline intersection profiles.
///
/// These exist because the four *device-class* profiles in BaselineDeviceProfiles.h could not
/// close the capability-reporting gate. Those four are hand-authored from published
/// specifications, and across every field the requirement actually consults they are
/// near-identical — one assertion evaluated four times, authored by the same hand that wrote
/// the requirements. Nothing about that arrangement can discover a mistake.
///
/// The profiles here are different in kind. Each is the **intersection of a collection of real
/// vulkan.gpuinfo.org device reports**, aggregated by LunarG and shipped in the pinned Vulkan
/// SDK. That gives them three properties the hand-authored four do not have:
///
///   - **Traceable.** Every value below is transcribed from a named file at a recorded digest,
///     not recalled or inferred. The provenance is exact enough to re-check by hand.
///   - **Conservative.** An intersection is the common denominator of its collection, so a
///     requirement satisfied by the intersection is satisfied by *every* device in it. That is
///     a stronger statement than four individual profiles passing.
///   - **Genuinely different from one another.** They span Vulkan 1.1 to 1.4, so they exercise
///     both the accept and the reject path of `checkCapabilities` with real-derived data
///     rather than with a value chosen to make a test fail.
///
/// @par What these still cannot do
/// A profile is not a driver test, exactly as a device-class profile is not. It also cannot
/// speak to **queue families or memory heaps** — the profile schema does not describe them,
/// because they are per-device and per-surface facts rather than capability facts. See
/// @ref profileAnswerableRequirement for how that gap is handled without being laundered into
/// an assumption.
///
/// @par Provenance
/// Source: `VP_LUNARG_desktop_baseline.json`, from Vulkan SDK **1.4.357.0** — the SDK version
/// pinned in `docs/dependencies.md` — at
/// `$VULKAN_SDK/Config/VK_LAYER_KHRONOS_profiles/VP_LUNARG_desktop_baseline.json`.
///
/// SHA-256 `8b11b84d765a70c97c07643b2c8a158e3a7974fe720ae416a206de53aa9ee22b`.
///
/// LunarG's own description of every profile in that file: *"A profile generated by the
/// intersection of a collection of GPUInfo.org device reports to support a large number of
/// actual systems in the Vulkan ecosystem."*
///
/// The values are transcribed rather than parsed, because parsing JSON would mean adding a JSON
/// dependency under ADR 0007 for four integers and two booleans, and because the pure
/// capability test is deliberately runnable on a machine with no Vulkan SDK and no GPU at all.
/// The transcription is reproducible from the commands recorded in `evidence/p1b/B1/Index.md`,
/// and the digest above is what detects the file changing under a later SDK.

#pragma once

#include "Sol/Render/CapabilityRequirement.h"
#include "Sol/Render/DeviceCapabilities.h"

#include <string>
#include <vector>

namespace sol::test {

/// One LunarG intersection profile, reduced to the fields the requirement consults.
struct LunarGProfile {
    std::string label;
    /// Profile name exactly as it appears in the source file.
    std::string profileName;
    render::DeviceCapabilities capabilities;
    /// Whether `baselineRequirement()` should accept this profile, and why.
    ///
    /// Stated as an expectation rather than discovered by the test, so that a change in either
    /// the requirement set or the SDK's profiles has to be looked at by a person instead of
    /// silently re-baselining whatever the code now does.
    bool expectedAcceptable = true;
    std::string expectation;
};

namespace detail {

/// The two formats `baselineRequirement()` consults, as the profiles report them.
///
/// `D32_SFLOAT` is the entry that matters. It is the one requirement in the whole declaration
/// that can reject a *conformant* device — Vulkan mandates `D16_UNORM` for depth/stencil
/// attachment and then guarantees only that at least one of `X8_D24_UNORM_PACK32` and
/// `D32_SFLOAT` supports it. BaselineDeviceProfiles.h calls its own value here "the least
/// trustworthy number in this file".
///
/// All four LunarG blocks list `VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT` and
/// `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` under `VK_FORMAT_D32_SFLOAT`'s `optimalTilingFeatures`.
/// Because each block is an intersection, that means every device in each collection supports
/// it — which is what turns "believed to be supported" into a traceable statement.
inline std::vector<render::FormatSupport> profileFormats()
{
    return {
        {.name = "VK_FORMAT_D32_SFLOAT",
         .optimalTilingDepthStencilAttachment = true,
         .optimalTilingColorAttachment = false,
         .optimalTilingSampledImage = true},
        {.name = "VK_FORMAT_B8G8R8A8_SRGB",
         .optimalTilingDepthStencilAttachment = false,
         .optimalTilingColorAttachment = true,
         .optimalTilingSampledImage = true},
    };
}

/// `VK_KHR_swapchain` appears in all four blocks, at spec version 70 in each.
inline std::vector<std::string> profileExtensions()
{
    return {"VK_KHR_swapchain"};
}

/// Builds a profile-derived capabilities value.
///
/// @note `queueFamilies` and `memoryHeaps` are deliberately left **empty**. The profile schema
/// does not describe them, and populating them with plausible values would convert "the profile
/// is silent on this" into "the profile says this" — the precise failure this whole file exists
/// to correct. @ref profileAnswerableRequirement is what keeps that emptiness from being read as
/// a rejection.
inline render::DeviceCapabilities profileCapabilities(
    std::string name,
    render::ApiVersion apiVersion)
{
    render::DeviceCapabilities device;
    device.deviceName = std::move(name);
    device.kind = render::DeviceKind::Other; // An intersection has no device type.
    device.apiVersion = apiVersion;
    device.driverVersionText = "(intersection profile — no driver)";
    device.extensions = profileExtensions();
    device.formats = profileFormats();
    device.limits.maxImageDimension2D = 16384; // identical in all four blocks
    return device;
}

} // namespace detail

/// `baselineRequirement()` reduced to the subset a Vulkan profile can actually answer.
///
/// A profile describes API version, extensions, features, limits and format properties. It does
/// not describe queue families or memory heaps. Checking a profile against the full requirement
/// would therefore reject every profile for a missing graphics-and-present queue — a fact about
/// the schema, reported as though it were a fact about hardware.
///
/// The honest handling is to drop exactly the un-answerable clauses and to say which they are.
/// `testProfileReductionIsExactlyWhatWeThink` asserts the dropped set is the one named here, so
/// a requirement added later that profiles cannot answer breaks that test and forces a decision
/// rather than quietly shrinking what these profiles certify.
inline render::CapabilityRequirement profileAnswerableRequirement()
{
    render::CapabilityRequirement requirement = render::baselineRequirement();
    requirement.requiresGraphicsAndPresentQueue = false;
    requirement.minimumDeviceLocalMemoryBytes = 0;
    return requirement;
}

/// LunarG Vulkan Desktop Baseline 2022 — API 1.1.139.
///
/// **Expected to be rejected**, and this is the most informative profile in the file. ADR 0002
/// sets Vulkan 1.2 as the P1 candidate floor; the widely-deployed desktop baseline as LunarG
/// measured it in 2022 was still 1.1. So the floor is not free, and the cost is now a number
/// rather than an intuition: it excludes the 2022 intersection and is met from 2023 onward.
inline LunarGProfile desktopBaseline2022()
{
    return {.label = "LunarG desktop baseline 2022 (API 1.1.139)",
            .profileName = "VP_LUNARG_desktop_baseline_2022",
            .capabilities = detail::profileCapabilities("LunarG desktop baseline 2022",
                                                        {1, 1, 139}),
            .expectedAcceptable = false,
            .expectation = "rejected: below ADR 0002's Vulkan 1.2 floor. This is the floor's "
                           "cost, stated as evidence rather than assumed away."};
}

/// LunarG Vulkan Desktop Baseline 2023 — API 1.2.148.
///
/// The first desktop-baseline intersection that clears ADR 0002's floor.
inline LunarGProfile desktopBaseline2023()
{
    return {.label = "LunarG desktop baseline 2023 (API 1.2.148)",
            .profileName = "VP_LUNARG_desktop_baseline_2023",
            .capabilities = detail::profileCapabilities("LunarG desktop baseline 2023",
                                                        {1, 2, 148}),
            .expectedAcceptable = true,
            .expectation = "accepted: first intersection at or above the 1.2 floor"};
}

/// LunarG Vulkan Desktop Baseline 2024 — API 1.2.197.
inline LunarGProfile desktopBaseline2024()
{
    return {.label = "LunarG desktop baseline 2024 (API 1.2.197)",
            .profileName = "VP_LUNARG_desktop_baseline_2024",
            .capabilities = detail::profileCapabilities("LunarG desktop baseline 2024",
                                                        {1, 2, 197}),
            .expectedAcceptable = true,
            .expectation = "accepted"};
}

/// LunarG Vulkan Desktop Baseline 2026 — API 1.4.304.
inline LunarGProfile desktopBaseline2026()
{
    return {.label = "LunarG desktop baseline 2026 (API 1.4.304)",
            .profileName = "VP_LUNARG_desktop_baseline_2026",
            .capabilities = detail::profileCapabilities("LunarG desktop baseline 2026",
                                                        {1, 4, 304}),
            .expectedAcceptable = true,
            .expectation = "accepted"};
}

/// Every LunarG desktop-baseline intersection in the pinned SDK, oldest first.
inline std::vector<LunarGProfile> allLunarGProfiles()
{
    return {desktopBaseline2022(),
            desktopBaseline2023(),
            desktopBaseline2024(),
            desktopBaseline2026()};
}

} // namespace sol::test
