#include "Sol/Proto/Frames/ReferenceData.h"

#include "Sol/Proto/Frames/Sha256.h"
#include "Sol/Proto/Frames/TextKernel.h"

#include <algorithm>
#include <array>
#include <charconv>
#include <cmath>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <utility>

namespace sol::proto::frames {
namespace {

/// One checked-in fixture and the digest it is expected to have.
///
/// The digests live in source rather than in a sidecar file so that changing reference data
/// forces a visible code change in the same review. A checksum manifest that travels with the
/// data it protects can be regenerated by the same command that corrupted the data.
struct ExpectedFixture {
    const char* relativePath;
    const char* role;
    const char* sourceUrl;
    const char* sha256;
};

constexpr std::array<ExpectedFixture, 7> kExpectedFixtures{{
    {"kernels/naif0012.tls",
     "leap seconds and TDB coefficients (SPICE LSK)",
     "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls",
     "678e32bdb5a744117a467cd9601cd6b373f0e9bc9bbde1371d5eee39600a039b"},
    {"kernels/pck00011.tpc",
     "IAU body shape and orientation constants (SPICE PCK)",
     "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc",
     "3dff7b1dbeceaa01f25467767d3fa25816051c85d162d1edf04acb310ee28bb1"},
    {"kernels/gm_de440.tpc",
     "DE440 gravitational parameters (SPICE PCK)",
     "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de440.tpc",
     "924ddf4fb9ead9fe8a1aa55780bcabde40b09d00065d58226e24b68d8092f140"},
    {"horizons/ssb-sun.txt",
     "Sun state relative to the Solar System barycentre, ICRF",
     "https://ssd.jpl.nasa.gov/api/horizons.api",
     "a2124d8896fa3f5d27c47aa78ff0c667665ffaf89d8e006cb73c78a425d0c218"},
    {"horizons/ssb-emb.txt",
     "Earth-Moon barycentre state relative to the Solar System barycentre, ICRF",
     "https://ssd.jpl.nasa.gov/api/horizons.api",
     "73dbc96ba0e1478b4db940f7fe2c92a82c7b965b19ed1c4bc21b17e6fcd24d4a"},
    {"horizons/ssb-earth.txt",
     "Earth state relative to the Solar System barycentre, ICRF",
     "https://ssd.jpl.nasa.gov/api/horizons.api",
     "36b486dc26c703b8909d9c02af8d9c812f99ea0bc6a52af658939cba002900cb"},
    {"horizons/ssb-moon.txt",
     "Moon state relative to the Solar System barycentre, ICRF",
     "https://ssd.jpl.nasa.gov/api/horizons.api",
     "18c3099749c69534e5bd2497d9713385e8fa3597169ef26fa6f4dfbc3078c8c0"},
}};

[[nodiscard]] std::string trim(std::string_view text)
{
    const std::size_t begin = text.find_first_not_of(" \t\r\n");
    if (begin == std::string_view::npos) {
        return {};
    }
    const std::size_t end = text.find_last_not_of(" \t\r\n");
    return std::string{text.substr(begin, end - begin + 1)};
}

[[nodiscard]] double parseDouble(const std::string& token, const std::filesystem::path& path)
{
    const std::string text = trim(token);
    double value = 0.0;
    const char* first = text.data();
    const char* last = first + text.size();
    const auto [pointer, error] = std::from_chars(first, last, value);
    if (error != std::errc{} || pointer != last) {
        throw std::runtime_error("Horizons fixture " + path.string() + ": '" + text
                                 + "' is not a number");
    }
    return value;
}

/// Counts the significant decimal digits Horizons printed, so the precision budget can state
/// the resolution of its own reference data instead of assuming it is exact.
[[nodiscard]] int countSignificantDigits(std::string_view token)
{
    int digits = 0;
    bool seenNonZero = false;
    for (const char c : token) {
        if (c == 'E' || c == 'e') {
            break;
        }
        if (c >= '0' && c <= '9') {
            if (c != '0') {
                seenNonZero = true;
            }
            if (seenNonZero) {
                ++digits;
            }
        }
    }
    return digits;
}

[[nodiscard]] std::string extractHeaderValue(const std::vector<std::string>& lines,
                                             std::string_view prefix)
{
    for (const std::string& line : lines) {
        if (line.rfind(prefix, 0) == 0) {
            const std::size_t colon = line.find(':');
            if (colon != std::string::npos) {
                return trim(std::string_view{line}.substr(colon + 1));
            }
        }
    }
    return {};
}

/// Pulls the `{source: DE441}` annotation out of a Horizons header line.
[[nodiscard]] std::string extractEphemerisSource(const std::string& targetLine)
{
    const std::size_t open = targetLine.find("{source:");
    if (open == std::string::npos) {
        return "unstated";
    }
    const std::size_t close = targetLine.find('}', open);
    if (close == std::string::npos) {
        return "unstated";
    }
    return trim(std::string_view{targetLine}.substr(open + 8, close - open - 8));
}

/// Pulls the NAIF integer id out of a name like `Earth (399)`.
[[nodiscard]] int extractNaifId(const std::string& targetName)
{
    const std::size_t open = targetName.rfind('(');
    const std::size_t close = targetName.rfind(')');
    if (open == std::string::npos || close == std::string::npos || close < open) {
        return 0;
    }
    const std::string digits = trim(std::string_view{targetName}.substr(open + 1, close - open - 1));
    int value = 0;
    const auto [pointer, error] =
        std::from_chars(digits.data(), digits.data() + digits.size(), value);
    if (error != std::errc{} || pointer != digits.data() + digits.size()) {
        return 0;
    }
    return value;
}

} // namespace

BodyStateFixture parseHorizonsVectorTable(const std::filesystem::path& path)
{
    std::ifstream file(path);
    if (!file) {
        throw std::runtime_error("Horizons fixture: cannot open " + path.string());
    }

    std::vector<std::string> lines;
    std::string line;
    while (std::getline(file, line)) {
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        lines.push_back(line);
    }

    BodyStateFixture fixture;

    const std::string targetName = extractHeaderValue(lines, "Target body name");
    fixture.bodyName = targetName;
    fixture.naifId = extractNaifId(targetName);
    fixture.centreName = extractHeaderValue(lines, "Center body name");
    fixture.referenceFrame = extractHeaderValue(lines, "Reference frame");

    for (const std::string& candidate : lines) {
        if (candidate.rfind("Target body name", 0) == 0) {
            fixture.ephemerisSource = extractEphemerisSource(candidate);
            break;
        }
    }

    if (fixture.naifId == 0 || fixture.referenceFrame.empty()) {
        throw std::runtime_error("Horizons fixture " + path.string()
                                 + ": header is missing the target id or reference frame");
    }
    if (fixture.referenceFrame != "ICRF") {
        throw std::runtime_error("Horizons fixture " + path.string() + ": reference frame is '"
                                 + fixture.referenceFrame + "', expected ICRF");
    }

    // ADR 0008 requires reference states at a TDB boundary. Horizons states the units and the
    // aberration treatment in its own trailer, and both are checked rather than assumed: a
    // table generated with light-time corrections would be a physically different quantity
    // that differs by hundreds of kilometres and still parses cleanly.
    const std::string outputUnits = extractHeaderValue(lines, "Output units");
    if (outputUnits.rfind("KM-S", 0) != 0) {
        throw std::runtime_error("Horizons fixture " + path.string() + ": output units are '"
                                 + outputUnits + "', expected KM-S");
    }
    const bool geometric =
        std::any_of(lines.begin(), lines.end(), [](const std::string& candidate) {
            return candidate.find("Geometric state vectors have NO corrections") != std::string::npos;
        });
    if (!geometric) {
        throw std::runtime_error("Horizons fixture " + path.string()
                                 + ": table does not declare uncorrected geometric states");
    }

    const auto startMarker = std::find(lines.begin(), lines.end(), "$$SOE");
    const auto endMarker = std::find(lines.begin(), lines.end(), "$$EOE");
    if (startMarker == lines.end() || endMarker == lines.end() || endMarker <= startMarker + 1) {
        throw std::runtime_error("Horizons fixture " + path.string() + ": no $$SOE/$$EOE block");
    }
    if (endMarker != startMarker + 2) {
        throw std::runtime_error("Horizons fixture " + path.string()
                                 + ": expected exactly one epoch in the table");
    }

    std::vector<std::string> fields;
    std::stringstream row(*(startMarker + 1));
    std::string field;
    while (std::getline(row, field, ',')) {
        fields.push_back(field);
    }
    if (fields.size() < 8) {
        throw std::runtime_error("Horizons fixture " + path.string()
                                 + ": vector row has too few columns");
    }

    fixture.epoch = TdbEpoch::fromJulianDate(parseDouble(fields[0], path));
    fixture.calendarTdb = trim(fields[1]);
    fixture.position = PositionMetres::fromKilometres(Vec3{parseDouble(fields[2], path),
                                                           parseDouble(fields[3], path),
                                                           parseDouble(fields[4], path)});
    fixture.velocity = VelocityMetresPerSecond::fromKilometresPerSecond(
        Vec3{parseDouble(fields[5], path), parseDouble(fields[6], path),
             parseDouble(fields[7], path)});
    fixture.printedSignificantDigits = countSignificantDigits(trim(fields[2]));

    return fixture;
}

ReferenceData ReferenceData::loadFromDirectory(const std::filesystem::path& fixtureRoot,
                                               bool verifyChecksums)
{
    ReferenceData data;

    for (const ExpectedFixture& expected : kExpectedFixtures) {
        const std::filesystem::path path = fixtureRoot / expected.relativePath;
        if (!std::filesystem::exists(path)) {
            throw std::runtime_error("ReferenceData: missing fixture " + path.string());
        }

        FixtureProvenance record;
        record.fileName = expected.relativePath;
        record.role = expected.role;
        record.sourceUrl = expected.sourceUrl;
        record.expectedSha256 = expected.sha256;
        record.actualSha256 = sha256HexOfFile(path);

        if (verifyChecksums && record.actualSha256 != record.expectedSha256) {
            throw std::runtime_error("ReferenceData: " + path.string()
                                     + " has digest " + record.actualSha256 + ", expected "
                                     + record.expectedSha256
                                     + ". The fixture and the results derived from it no longer"
                                       " match; re-run the acquisition step and update the"
                                       " recorded digest deliberately.");
        }
        data.m_provenance.push_back(std::move(record));
    }

    const TextKernel leapSecondKernel =
        TextKernel::loadFromFile(fixtureRoot / "kernels/naif0012.tls");
    data.m_timeScales = TimeScales::fromLeapSecondKernel(leapSecondKernel);

    const TextKernel planetaryConstants =
        TextKernel::loadFromFile(fixtureRoot / "kernels/pck00011.tpc");
    const std::vector<double> radii = planetaryConstants.numbers("BODY399_RADII", 3);
    if (radii[0] != radii[1]) {
        throw std::runtime_error(
            "ReferenceData: BODY399_RADII is triaxial; the biaxial Ellipsoid type would silently"
            " discard the second equatorial radius");
    }
    data.m_earthEllipsoid =
        Ellipsoid::fromRadiiKilometres("IAU Earth (pck00011 BODY399_RADII)", radii[0], radii[2]);

    const std::vector<double> poleRa = planetaryConstants.numbers("BODY399_POLE_RA", 3);
    const std::vector<double> poleDec = planetaryConstants.numbers("BODY399_POLE_DEC", 3);
    const std::vector<double> primeMeridian = planetaryConstants.numbers("BODY399_PM", 3);
    for (std::size_t i = 0; i < 3; ++i) {
        data.m_poleRa[i] = poleRa[i];
        data.m_poleDec[i] = poleDec[i];
        data.m_primeMeridian[i] = primeMeridian[i];
    }

    const TextKernel gravitationalKernel =
        TextKernel::loadFromFile(fixtureRoot / "kernels/gm_de440.tpc");
    for (const int naifId : {3, 10, 301, 399}) {
        const std::string name = "BODY" + std::to_string(naifId) + "_GM";
        // km^3/s^2 to m^3/s^2 at the data boundary, once, where the unit is still visible.
        data.m_gravitationalParameters.emplace_back(naifId, gravitationalKernel.number(name) * 1e9);
    }

    for (const char* relativePath : {"horizons/ssb-sun.txt", "horizons/ssb-emb.txt",
                                     "horizons/ssb-earth.txt", "horizons/ssb-moon.txt"}) {
        data.m_bodyStates.push_back(parseHorizonsVectorTable(fixtureRoot / relativePath));
    }

    data.m_fixtureEpoch = data.m_bodyStates.front().epoch;
    for (const BodyStateFixture& state : data.m_bodyStates) {
        if (state.epoch.secondsPastJ2000() != data.m_fixtureEpoch.secondsPastJ2000()) {
            throw std::runtime_error("ReferenceData: body fixtures are at different epochs; they"
                                     " cannot be differenced into one frame graph");
        }
        if (state.centreName.rfind("Solar System Barycenter", 0) != 0) {
            throw std::runtime_error("ReferenceData: " + state.bodyName + " is centred on '"
                                     + state.centreName + "', expected the barycentre");
        }
    }

    return data;
}

double ReferenceData::gravitationalParameter(int naifId) const
{
    const auto found = std::find_if(
        m_gravitationalParameters.begin(), m_gravitationalParameters.end(),
        [naifId](const std::pair<int, double>& entry) { return entry.first == naifId; });
    if (found == m_gravitationalParameters.end()) {
        throw std::runtime_error("ReferenceData: no GM for NAIF id " + std::to_string(naifId));
    }
    return found->second;
}

const BodyStateFixture& ReferenceData::bodyState(int naifId) const
{
    const auto found = std::find_if(
        m_bodyStates.begin(), m_bodyStates.end(),
        [naifId](const BodyStateFixture& state) { return state.naifId == naifId; });
    if (found == m_bodyStates.end()) {
        throw std::runtime_error("ReferenceData: no body state for NAIF id "
                                 + std::to_string(naifId));
    }
    return *found;
}

std::filesystem::path parseFixtureRoot(int argc, char** argv)
{
    for (int i = 1; i < argc; ++i) {
        if (std::string_view{argv[i]} == "--fixtures") {
            if (i + 1 >= argc) {
                throw std::invalid_argument("--fixtures requires a directory path");
            }
            return std::filesystem::path{argv[i + 1]};
        }
    }
#ifdef SOL_PROTO_FIXTURE_ROOT
    return std::filesystem::path{SOL_PROTO_FIXTURE_ROOT};
#else
#error "SOL_PROTO_FIXTURE_ROOT is not defined; the Frames library's CMake target must define it"
#endif
}

Geodetic ReferenceData::launchAnchor() noexcept
{
    Geodetic anchor;
    anchor.latitude = Radians::fromDegrees(28.0);
    anchor.longitude = Radians::fromDegrees(-80.5);
    anchor.heightMetres = 5.0;
    return anchor;
}

} // namespace sol::proto::frames
